/**
 * app.js
 * Entry point for THE LEXICON.
 * Orchestrates module initialization and global event delegation.
 */

// archiveData is populated asynchronously by loadArchiveData() below.
// All module-level callbacks close over this binding by reference, so they
// receive the live value once DOMContentLoaded resolves it.
let archiveData = [];

const FOCUSABLE_SELECTORS = 'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
import { imageDimensions } from './modules/image-dimensions.js';
import { $, $$, debounce, initCustomCursor, showToast, resolveImgSrc, setImageDimensions, webpSrc } from './modules/core-utils.js';
setImageDimensions(imageDimensions);
import { AppState, updateHash, emptyFilters } from './modules/core-state.js';
import { renderTaxonomyGrid, renderTaxonomySub, getFilteredEntries, setActiveTaxonomy, invalidateSearchCache } from './modules/search-engine.js';
import { renderImageGrid, renderEntryList, renderFeaturedStrip } from './modules/render-grid.js';
import { openDetail, closeDetail, navigateEntry, updateStatusBar } from './modules/render-detail.js';
import { initHotspotInteractions, cleanupHotspots, toggleMobileHotspots } from './modules/hotspots.js';
// sticky-notes module reserved for future use; previous exports were dead.
import { switchView } from './modules/navigation.js';
import { openConnectionMatrix, closeConnectionMatrix } from './modules/connection-matrix.js';
import { initHeaderTypewriter, updateHeaderTelemetry } from './modules/telemetry.js';
import { initFirebaseAuth, toggleAuth, sendSignInLink, createArchivalFolder, saveToFolder, currentUser, fetchArchivalFolders } from './modules/auth.js';
import { addRecentlyViewed, toggleBookmark, isBookmarked } from './modules/storage.js';
import { toggleCmdPalette, handleCmdKeydown, renderCmdResults } from './modules/command-palette.js';
import { renderTimeline, renderFilterChips, updateMetaForEntry, resetMeta, extractAccentColor } from './modules/ui-extras.js';
import { getTranslation, supportedLanguages } from './modules/translations.js';
import { renderIndexView, setViewMode, getViewMode, applyViewMode, indexNavigateRow, indexActivateRow, getTagCategory } from './modules/render-index-view.js';

// --- Shared Callbacks ---
const callbacks = {
  openDetail: (id, idx = 0) => openDetail(id, idx, archiveData, callbacks),
  closeDetail: () => closeDetail(callbacks, archiveData),
  navigateEntry: (dir) => navigateEntry(dir, archiveData, callbacks),
  showToast: showToast,
  renderFolders: () => renderFoldersView(),
  renderFolderOptions: () => { openModal('save-folder-modal'); renderSaveFolderModal(); },
  updateBookmarkUI: (id) => {
    const btn = $('btn-bookmark-entry');
    const saved = isBookmarked(id);
    if (btn) {
      btn.style.opacity = saved ? '1' : '0.4';
      btn.setAttribute('aria-pressed', String(saved));
    }
  },
  closeModal: (id) => {
    const modal = $(id + '-modal');
    if (modal) modal.classList.add('hidden');
  },
  updateHeaderTelemetry: updateHeaderTelemetry,
  addRecentlyViewed: (id) => addRecentlyViewed(id, archiveData, callbacks),
  updateMetaForEntry: updateMetaForEntry,
  extractAccentColor: extractAccentColor,
  resetMeta: resetMeta,
  switchView: (view) => switchView(view, callbacks),
  onUpdate: () => refreshUI()
};

// ── Data loading ─────────────────────────────────────────────────────────────
/**
 * Resolves archiveData from Supabase when configured, or falls back to the
 * static database.js. Either way, archiveData is populated before any UI
 * rendering happens in DOMContentLoaded.
 */
async function loadArchiveData() {
  try {
    const { fetchArchiveData } = await import('./modules/supabase-client.js');
    const remote = await fetchArchiveData();
    if (remote && remote.length > 0) {
      archiveData = remote;
      console.log(`[LEXICON] Loaded ${archiveData.length} entries from Supabase.`);
      return;
    }
  } catch (err) {
    console.warn('[LEXICON] Supabase unavailable — falling back to database.js:', err.message);
  }
  // Static fallback: database.js is always available (generated by preflight)
  const { archiveData: staticData } = await import('../database.js?v=66989e7');
  archiveData = staticData;
  console.log(`[LEXICON] Loaded ${archiveData.length} entries from database.js.`);
}

// --- Initialization ---
window.addEventListener('hashchange', handleRouting);
document.addEventListener('DOMContentLoaded', async () => {
  // FIX-5: Bind UI events immediately so buttons work even if init throws
  setupEventListeners();
  try {
  // Resolve archive data before any rendering (Supabase → database.js fallback)
  await loadArchiveData();
  if (!archiveData || archiveData.length === 0) return;

  // Initial State
  AppState.archivalFolders = fetchArchivalFolders();

  // Systems
  initCustomCursor();
  initHeaderTypewriter(archiveData);
  // Pass archiveData to hotspots so it doesn't need to import database.js itself
  initHotspotInteractions(archiveData);
  initFirebaseAuth(callbacks);

  // Phase 1/2: Restore view mode preference (visual | index) from localStorage
  applyViewMode(getViewMode());

  // Listeners
  // setupEventListeners() already called at top of DOMContentLoaded (FIX-5)
  handleRouting();

  // Initial Render
  refreshUI();
  renderHero(archiveData);
  syncMobileSheetChips();

  // Orientation Panel Logic
  var dismissed;
  try { dismissed = localStorage.getItem('lexicon-orientation-dismissed'); } catch(e) {}
  if (dismissed) {
    const op = $('orientation-panel');
    if (op) op.classList.add('hidden');
  }

  // Reveal UI
  setTimeout(() => {
    const overlay = $('boot-overlay');
    const root = $('app-root');
    if (overlay) {
      overlay.style.opacity = '0';
      setTimeout(() => {
        overlay.classList.add('hidden');
        if (root) root.classList.remove('opacity-0');
      }, 300);
    } else if (root) {
      root.classList.remove('opacity-0');
    }
  }, 500);
    } catch(e) { console.error('LEXICON_BOOT_ERROR:', e); }
});

// ─────────────────────────────────────────────────────────────────────
// REFRESH PIPELINE
// Split into three layers so hot paths (search keystroke, sort cycle,
// filter chip toggle) don't re-render invariant chrome:
//
//   refreshChrome()   button labels + modal bodies + sort label — only
//                     changes on language switch or auth state change.
//                     Rebuilds 5 modal innerHTMLs, so keep it off hot paths.
//
//   refreshTaxonomy() #taxonomy-grid + #taxonomy-sub — fires when the
//                     active category or applied filter changes.
//
//   refreshContent()  grid view + entry list + filter chips + status bar
//                     — fires on search / sort / filter / folder mutation.
//
//   refreshUI()       calls all three; safe fallback for any caller that
//                     doesn't know which subset it actually changed.
// ─────────────────────────────────────────────────────────────────────

function refreshChrome() {
  const lang = AppState.language;
  const t = (key) => getTranslation(key, lang);

  // --- Header ---
  const btnAuth = $('btn-auth-toggle');
  const btnAuthMobile = $('btn-auth-toggle-mobile');
  const authText = currentUser ? t('nav_signout') : t('nav_signin');
  if (btnAuth) btnAuth.textContent = authText.toUpperCase();
  if (btnAuthMobile) btnAuthMobile.textContent = authText.toUpperCase();

  const btnAbout = $('btn-about');
  const btnAboutMobile = $('btn-about-mobile');
  if (btnAbout) btnAbout.textContent = t('nav_about').toUpperCase();
  if (btnAboutMobile) btnAboutMobile.textContent = t('nav_about_mobile').toUpperCase();

  const btnContact = $('btn-contact');
  const btnContactMobile = $('btn-contact-mobile');
  if (btnContact) btnContact.textContent = t('nav_contact').toUpperCase();
  if (btnContactMobile) btnContactMobile.textContent = t('nav_contact_mobile').toUpperCase();

  const btnLangLabel = $('btn-lang-toggle-label');
  const btnLangMobile = $('btn-lang-toggle-mobile');
  if (btnLangLabel) btnLangLabel.textContent = lang.toUpperCase() + ' ▾';
  if (btnLangMobile) btnLangMobile.textContent = (t('nav_language') + ': ' + lang.toUpperCase()).toUpperCase();
  renderLangDropdown();

  const btnTheme = $('btn-theme-toggle');
  const btnThemeMobile = $('btn-theme-toggle-mobile');
  const isDark = document.documentElement.classList.contains('dark');
  const themeText = isDark ? t('nav_theme_dark') : t('nav_theme_light');
  if (btnTheme) btnTheme.textContent = themeText.toUpperCase();
  if (btnThemeMobile) btnThemeMobile.textContent = t('nav_theme_mobile').toUpperCase();

  const btnFoldersMobile = $('btn-folders-toggle-mobile');
  if (btnFoldersMobile) btnFoldersMobile.textContent = t('nav_folders_mobile').toUpperCase();

  // Telemetry text is owned by initHeaderTypewriter — overwriting it
  // every keystroke/filter change made the typewriter flicker. The
  // typewriter handles language switches on its own next tick.

  // --- Index Panel ---
  const indexTitle = $('index-panel-title');
  if (indexTitle) indexTitle.textContent = t('index_title');

  const btnBookmarks = $('btn-show-bookmarks');
  if (btnBookmarks) btnBookmarks.textContent = t('index_saved');

  const recentTitle = $('recent-title-label');
  if (recentTitle) recentTitle.textContent = t('index_recent');

  const searchInput = $('search-input');
  if (searchInput) {
    // Mobile gets a shorter placeholder so it doesn't truncate behind
    // the CLEAR button — the full prompt only fits on desktop.
    const fullPh  = t('search_placeholder');
    const shortPh = t('search_placeholder_short') || 'Search archive…';
    searchInput.placeholder = window.innerWidth < 768 ? shortPh : fullPh;
  }

  const btnClearDir = $('btn-clear-directory');
  if (btnClearDir) btnClearDir.textContent = t('search_clear');

  // --- Status Ribbon labels (Brand/Year/Season/Entry sub-labels) ---
  const statusLabels = {
    'status-brand-label':  'status_brand',
    'status-year-label':   'status_year',
    'status-season-label': 'status_season',
    'status-entry-label':  'status_entry'
  };
  Object.entries(statusLabels).forEach(([id, key]) => {
    const el = $(id);
    if (el) el.textContent = t(key);
  });

  // --- View switcher ---
  const btnGrid     = $('btn-toggle-grid');
  const btnTimeline = $('btn-toggle-timeline');
  if (btnGrid)     btnGrid.textContent     = t('label_grid_view');
  if (btnTimeline) btnTimeline.textContent = t('label_timeline');

  // --- Orientation panel (hero layout) — text is baked into HTML; no dynamic i18n needed here ---
  const btnDismissOri = $('btn-dismiss-orientation');
  if (btnDismissOri) btnDismissOri.textContent = t('orientation_proceed') || 'BROWSE THE ARCHIVE →';

  // --- Active Entry Detail ---
  const btnSaveFolder       = $('btn-save-to-folder');
  if (btnSaveFolder) btnSaveFolder.textContent = t('btn_save_folder');
  // Mobile action-bar buttons use icon + short label structure. Target
  // only the .btn-label-mobile child so the icon span is preserved and
  // the short label doesn't wrap at 65px column width.
  const setMobileLabel = (btnId, shortKey) => {
    const span = document.querySelector('#' + btnId + ' .btn-label-mobile');
    if (span) span.textContent = t(shortKey);
  };
  setMobileLabel('btn-save-folder-mobile',     'btn_save_mobile');
  setMobileLabel('btn-notes-mobile',           'btn_notes_mobile');
  setMobileLabel('btn-toggle-hotspots-mobile', 'btn_hotspots_mobile_short');
  setMobileLabel('btn-nexus-mobile',           'btn_nexus_mobile');
  setMobileLabel('btn-back-grid-mobile',       'btn_back_mobile');

  const btnNexus = $('btn-open-matrix');
  if (btnNexus) btnNexus.textContent = t('btn_view_nexus');

  const btnCopyLink = $('btn-copy-link');
  if (btnCopyLink) btnCopyLink.textContent = t('btn_copy_link');

  const btnCite = $('btn-cite-entry');
  if (btnCite) btnCite.textContent = t('btn_cite_entry');
  const citeTitle = $('cite-modal-title');
  if (citeTitle) citeTitle.textContent = t('cite_modal_title');
  const citeSub = $('cite-modal-subtitle');
  if (citeSub) citeSub.textContent = t('cite_modal_subtitle');
  const citeChicago = $('cite-chicago-label');
  if (citeChicago) citeChicago.textContent = t('cite_chicago_label');
  const citeBibtex = $('cite-bibtex-label');
  if (citeBibtex) citeBibtex.textContent = t('cite_bibtex_label');
  const citeUrl = $('cite-url-label');
  if (citeUrl) citeUrl.textContent = t('cite_url_label');
  document.querySelectorAll('.cite-copy-btn').forEach(b => {
    if (!b.classList.contains('btn-copied')) b.textContent = t('cite_copy');
  });

  const btnBackGrid = $('btn-back-grid');
  if (btnBackGrid) btnBackGrid.textContent = t('btn_back_grid');

  const btnFullscreen = $('btn-fullscreen-toggle');
  if (btnFullscreen) btnFullscreen.textContent = '[ ' + t('btn_fullscreen') + ' ]';

  const payloadLabel = $$('#analytical-payload .node-label')[0];
  if (payloadLabel) payloadLabel.textContent = '[ ' + t('label_analysis') + ' ]';

  // --- Mobile detail actions ---
  // (btn-toggle-hotspots-mobile label handled by setMobileLabel above — DON'T
  // overwrite the whole textContent here, that destroys the icon+label structure.)

  // --- Technical specs label ---
  const techSpecsLabel = $$('#detail-metadata-sidebar h4')[0];
  if (techSpecsLabel) techSpecsLabel.textContent = t('tech_specs');

  // --- Related entries label ---
  const relatedLabel = $('related-entries-title');
  if (relatedLabel) relatedLabel.textContent = t('related_artifacts');

  // --- Mobile drawer search button ---
  const btnSearchMobile = $('btn-search-mobile');
  if (btnSearchMobile) btnSearchMobile.textContent = t('btn_search_mobile');


  // --- Folders View ---
  const folderTitle = $$('#folders-view h1')[0];
  if (folderTitle) folderTitle.textContent = t('folders_title');

  const btnExport = $('btn-export-all-folders');
  if (btnExport) btnExport.textContent = t('folders_export');

  const folderCount = $('folders-count');
  if (folderCount) folderCount.textContent = `${AppState.archivalFolders.length} ${t('folders_initialized')}`;

  const btnClearFolderFilter = $('btn-clear-folder-filter');
  if (btnClearFolderFilter) btnClearFolderFilter.textContent = t('btn_clear_filter');

  // --- Modals ---
  const bootText = $('boot-text');
  if (bootText) bootText.textContent = t('loading');

  const cookieText = $('cookie-notice-text');
  if (cookieText) cookieText.textContent = t('cookie_notice');

  const btnAcceptCookies = $('btn-accept-cookies');
  if (btnAcceptCookies) btnAcceptCookies.textContent = t('accept_terms');

  // Auth Modal
  const authTitle = $$('#auth-modal h2')[0];
  if (authTitle) authTitle.textContent = t('modal_terminal_access');

  const authDesc = $$('#auth-form-container p')[0];
  if (authDesc) authDesc.textContent = t('modal_auth_desc');

  const btnSubmitAuth = $('btn-submit-auth');
  if (btnSubmitAuth) btnSubmitAuth.textContent = t('modal_auth_transmit');

  // Save to Folder Modal
  const saveFolderTitle = $$('#save-folder-modal h2')[0];
  if (saveFolderTitle) saveFolderTitle.textContent = t('btn_save_folder');

  const newFolderLabel = $$('#save-folder-modal label')[0];
  if (newFolderLabel) newFolderLabel.textContent = t('btn_initialize').replace('[ ', '').replace(' ]', '');

  const btnInitialize = $('btn-create-folder');
  if (btnInitialize) btnInitialize.textContent = t('btn_initialize');

  // About Modal
  const aboutTitle = $('about-modal-title');
  if (aboutTitle) aboutTitle.textContent = t('modal_about_title');

  const aboutBody = $('about-modal-body');
  if (aboutBody) {
    aboutBody.innerHTML = t('modal_about_body').map(p => `<p>${p}</p>`).join('');
  }

  // Contact Modal
  const contactTitle = $('contact-modal-title');
  if (contactTitle) contactTitle.textContent = t('modal_contact_title');

  const contactBody = $('contact-modal-body');
  if (contactBody) {
    contactBody.innerHTML = t('modal_contact_body').map(p => `<p>${p}</p>`).join('');
  }

  // Legal Modals
  const privacyTitle = $('privacy-modal-title');
  if (privacyTitle) privacyTitle.textContent = t('legal_privacy_title');

  const privacyBody = $('privacy-modal-body');
  if (privacyBody) {
    privacyBody.innerHTML = t('legal_privacy_body').map(p => `<p>${p}</p>`).join('');
  }

  const termsTitle = $('terms-modal-title');
  if (termsTitle) termsTitle.textContent = t('legal_terms_title');

  const termsBody = $('terms-modal-body');
  if (termsBody) {
    termsBody.innerHTML = t('legal_terms_body').map(p => `<p>${p}</p>`).join('');
  }

  // --- Sort Button label (the active sort value is content, but the
  //     "SORT:" prefix is chrome — including it here keeps the
  //     translation in one place; rebuilding is trivial).
  const sortBtn = $('btn-sort-cycle');
  if (sortBtn) {
    const sortLabels = {
      'default':   t('sort_default'),
      'year-asc':  t('sort_year_asc'),
      'year-desc': t('sort_year_desc'),
      'brand-az':  t('sort_brand_az')
    };
    const currentSortLabel = sortLabels[AppState.sortMode || 'default'] || t('sort_default');
    sortBtn.textContent = `${t('sort_label')}: ${currentSortLabel}`;
  }
}

function refreshTaxonomy() {
  const lang = AppState.language;
  const taxHeading = $('taxonomy-heading');
  if (taxHeading) taxHeading.textContent = getTranslation('taxonomy_heading', lang) || 'Categories';
  renderTaxonomyGrid();
  renderTaxonomySub(callbacks, archiveData);
}

function refreshSortLabel() {
  const lang = AppState.language;
  const t = (key) => getTranslation(key, lang);
  const sortBtn = $('btn-sort-cycle');
  if (!sortBtn) return;
  const sortLabels = {
    'default':   t('sort_default'),
    'year-asc':  t('sort_year_asc'),
    'year-desc': t('sort_year_desc'),
    'brand-az':  t('sort_brand_az')
  };
  const currentSortLabel = sortLabels[AppState.sortMode || 'default'] || t('sort_default');
  sortBtn.textContent = `${t('sort_label')}: ${currentSortLabel}`;
}

function refreshContent() {
  syncHashFromState();
  refreshSortLabel();
  const filtered = getFilteredEntries(archiveData);
  renderEntryList(archiveData, callbacks);

  if (AppState.currentView === 'grid') {
    renderImageGrid(archiveData, callbacks);
    renderFeaturedStrip(archiveData);
    // Phase 2: also render the Brutalist Index View (toggled by V/I)
    // resetPage=true so filter changes always go back to page 1
    renderIndexView(archiveData, true);
  } else if (AppState.currentView === 'timeline') {
    renderTimeline(filtered, callbacks);
  } else if (AppState.currentView === 'folders') {
    if (callbacks.renderFolders) callbacks.renderFolders();
  }

  renderFilterChips(callbacks);
  updateStatusBar(archiveData);

  // Update filtered result count badge in the filter chip bar
  const countEl = $('filter-result-count');
  const filteredEntries = getFilteredEntries(archiveData);
  if (countEl) {
    const hasFilter = filteredEntries.length !== archiveData.length;
    countEl.textContent = hasFilter ? `${filteredEntries.length} / ${archiveData.length} ENTRIES` : '';
    countEl.classList.toggle('hidden', !hasFilter);
  }

  // Announce result count to screen readers when filters are active
  const announcer = $('aria-announcer');
  if (announcer) {
    const hasActiveFilter = filteredEntries.length !== archiveData.length
      || Object.values(AppState.filters).some(Boolean)
      || AppState.searchQuery;
    announcer.textContent = hasActiveFilter
      ? `${filteredEntries.length} entries shown`
      : '';
  }
}

function refreshUI() {
  refreshChrome();
  refreshTaxonomy();
  refreshContent();
}

let _suppressHashSync = false;

function applyStateFromQuery(params) {
  if (params.has('sort')) AppState.sortMode = params.get('sort');
  if (params.has('q')) {
    AppState.searchQuery = params.get('q');
    const si = $('search-input');
    if (si) si.value = AppState.searchQuery;
  }
  for (const key of Object.keys(AppState.filters)) {
    if (params.has(key)) AppState.filters[key] = params.get(key);
  }
  // Year range from URL (y_min / y_max)
  const yMin = params.has('y_min') ? parseInt(params.get('y_min')) : 1980;
  const yMax = params.has('y_max') ? parseInt(params.get('y_max')) : 2025;
  if (!isNaN(yMin) && !isNaN(yMax)) AppState.yearRange = { min: yMin, max: yMax };

  // Phase 2: view mode (visual | index) is URL-shareable
  if (params.has('mode')) {
    const mode = params.get('mode');
    if (mode === 'index' || mode === 'visual') setViewMode(mode);
  }
}

export function syncHashFromState() {
  if (_suppressHashSync) return;
  // Detail view manages its own hash; don't overwrite it here.
  if (AppState.selectedEntryId) return;
  const params = new URLSearchParams();
  if (AppState.sortMode && AppState.sortMode !== 'default') params.set('sort', AppState.sortMode);
  if (AppState.searchQuery) params.set('q', AppState.searchQuery);
  for (const [k, v] of Object.entries(AppState.filters)) {
    if (v) params.set(k, v);
  }
  const yr = AppState.yearRange || { min: 1980, max: 2025 };
  if (yr.min > 1980) params.set('y_min', yr.min);
  if (yr.max < 2025) params.set('y_max', yr.max);
  // Phase 2: encode view mode (only if non-default)
  if (AppState.viewMode === 'index') params.set('mode', 'index');
  const view = AppState.currentView || 'grid';
  const qs = params.toString();
  const newHash = '#' + view + (qs ? '?' + qs : '');
  if (window.location.hash === newHash || (view === 'grid' && !qs && !window.location.hash)) return;
  _suppressHashSync = true;
  history.replaceState(null, '', window.location.pathname + window.location.search + newHash);
  setTimeout(() => { _suppressHashSync = false; }, 0);
}

function handleRouting() {
  if (_suppressHashSync) return;
  const raw = window.location.hash.slice(1); // strip #
  if (!raw) { switchView('grid', callbacks); return; }

  const [path, query] = raw.split('?');
  const params = new URLSearchParams(query || '');

  if (path.startsWith('detail/')) {
    const parts = path.replace('detail/', '').split('/');
    const id  = parts[0];
    const idx = parts[1] ? parseInt(parts[1]) : 0;
    openDetail(id, idx, archiveData, callbacks);
    return;
  }

  // Apply persisted filters/sort/search BEFORE switching view
  applyStateFromQuery(params);

  if (path === 'folders')   { switchView('folders', callbacks); return; }
  if (path === 'timeline')  { switchView('timeline', callbacks); return; }
  if (path === 'grid' || path === '') { switchView('grid', callbacks); return; }

  // Fallback: maybe it's a bare entry id
  const entry = archiveData.find(e => e.id === path);
  if (entry) {
    openDetail(path, 0, archiveData, callbacks);
  } else {
    switchView('grid', callbacks);
  }
}

function setupEventListeners() {
  // Global Click Delegation
  document.addEventListener('click', (e) => {

    // Grid Cell Click
    const gridCell = e.target.closest('.grid-cell');
    if (gridCell) {
      const id  = gridCell.dataset.entryId;
      const idx = gridCell.dataset.imgIndex || 0;
      window.location.hash = `detail/${id}/${idx}`;
      return;
    }

    // Entry Item Click (A-Z Index)
    const entryItem = e.target.closest('.entry-item');
    if (entryItem) {
      const id = entryItem.dataset.id;
      window.location.hash = `detail/${id}/0`;
      return;
    }

    // Recent Entry Click
    const recentItem = e.target.closest('[data-recent-id]');
    if (recentItem) {
      openDetail(recentItem.dataset.recentId, 0, archiveData, callbacks);
      return;
    }

    // ── Taxonomy Navigation ──────────────────────────────────────
    // Scope to the taxonomy section so unrelated buttons elsewhere with
    // overlapping data-attributes (filter chips, metadata tags, etc.)
    // don't accidentally toggle the filter panel.
    const inTaxonomy = e.target.closest('#taxonomy-grid, #taxonomy-sub');

    // Tier 1: category type button (has data-taxonomy-type but NOT data-taxonomy-val)
    const taxType = inTaxonomy ? e.target.closest('[data-taxonomy-type]') : null;
    if (taxType && !taxType.dataset.taxonomyVal) {
      const type = taxType.dataset.taxonomyType;
      setActiveTaxonomy(type);
      renderTaxonomyGrid();
      renderTaxonomySub(callbacks, archiveData);
      return;
    }

    // Tier 2: value button (has both data-taxonomy-type and data-taxonomy-val)
    // Allow these from anywhere — chips outside the taxonomy section
    // (e.g., metadata-tag-btn on detail view) should still apply filters.
    const taxVal = e.target.closest('[data-taxonomy-val]');
    if (taxVal) {
      const type = taxVal.dataset.taxonomyType;
      const val  = taxVal.dataset.taxonomyVal;
      // Multi-select: toggle this value within the pipe-separated filter string
      const current = AppState.filters[type] || '';
      const activeVals = current.split('|').map(s => s.trim()).filter(Boolean);
      const idx = activeVals.indexOf(val);
      if (idx >= 0) {
        activeVals.splice(idx, 1);
      } else {
        activeVals.push(val);
      }
      AppState.filters[type] = activeVals.length ? activeVals.join('|') : null;
      // Re-render sub-panel to update checked state; keep panel open for multi-select.
      renderTaxonomySub(callbacks, archiveData);
      renderTaxonomyGrid();
      refreshContent();
      updateHash('grid');
      return;
    }

    // Clear-all button for a single taxonomy axis
    const taxClear = e.target.closest('[data-taxonomy-clear]');
    if (taxClear) {
      AppState.filters[taxClear.dataset.taxonomyClear] = null;
      renderTaxonomySub(callbacks, archiveData);
      renderTaxonomyGrid();
      refreshContent();
      updateHash('grid');
      return;
    }

    // Back button inside taxonomy sub-panel
    if (e.target.closest('[data-taxonomy-back]') || e.target.id === 'btn-taxonomy-back') {
      AppState.activeTaxonomy = null;
      renderTaxonomyGrid();
      renderTaxonomySub(callbacks, archiveData);
      return;
    }
    // ────────────────────────────────────────────────────────────

  });

  // Header Title
  $('header-title')?.addEventListener('click', () => {
    AppState.filters = emptyFilters();
    AppState.searchQuery = '';
    AppState.activeFolderId = null;
    if ($('search-input')) $('search-input').value = '';
    // switchView triggers onUpdate→refreshUI at the end; no separate
    // refreshUI() needed here. But the categories cells reflect the
    // (now-empty) filter set, which switchView doesn't touch — flip
    // them via refreshTaxonomy after switchView's refreshUI runs.
    switchView('grid', callbacks);
    refreshTaxonomy();
    updateHash('grid');
  });

  // Toggles
  $('btn-folders-toggle')?.addEventListener('click', () => switchView('folders', callbacks));
  $('btn-folders-toggle-mobile')?.addEventListener('click', () => { switchView('folders', callbacks); toggleHamburger(); });
  $('btn-theme-toggle')?.addEventListener('click', toggleTheme);
  $('btn-lang-toggle')?.addEventListener('click', toggleLangDropdown);
  document.addEventListener('click', (e) => {
    const dd = $('lang-dropdown');
    if (!dd || dd.classList.contains('hidden')) return;
    if (!e.target.closest('#lang-dropdown') && !e.target.closest('#btn-lang-toggle')) {
      dd.classList.add('hidden');
      $('btn-lang-toggle')?.setAttribute('aria-expanded', 'false');
    }
  });
  $('btn-auth-toggle')?.addEventListener('click', () => {
    toggleAuth();
    const authModal = $('auth-modal');
    if (authModal && !authModal.classList.contains('hidden')) {
      setTimeout(() => $('auth-email')?.focus(), 50);
      trapFocus(authModal);
    }
  });
  $('btn-theme-toggle-mobile')?.addEventListener('click', toggleTheme);
  $('btn-lang-toggle-mobile')?.addEventListener('click', toggleLanguage);
  $('btn-auth-toggle-mobile')?.addEventListener('click', () => {
    toggleAuth();
    const authModal = $('auth-modal');
    if (authModal && !authModal.classList.contains('hidden')) {
      setTimeout(() => $('auth-email')?.focus(), 50);
      trapFocus(authModal);
    }
  });

  // Modals — opening
  function openModal(id) {
    const modal = $(id);
    if (!modal) return;
    modal.classList.remove('hidden');
    // Move focus to first focusable element (prefer close button)
    const focusEl = modal.querySelector('[data-modal-close], [autofocus]') || modal.querySelector(FOCUSABLE_SELECTORS);
    if (focusEl) requestAnimationFrame(() => focusEl.focus());
    trapFocus(modal);
  }
  $('btn-about')?.addEventListener('click', () => openModal('about-modal'));
  $('btn-contact')?.addEventListener('click', () => openModal('contact-modal'));
  $('btn-about-mobile')?.addEventListener('click', () => { openModal('about-modal'); toggleHamburger(); });
  $('btn-contact-mobile')?.addEventListener('click', () => { openModal('contact-modal'); toggleHamburger(); });
  $('btn-search-mobile')?.addEventListener('click', () => { const s = $('search-input'); if (s) { s.focus(); s.scrollIntoView({ behavior: 'smooth' }); } });
  $('btn-privacy-link')?.addEventListener('click', () => openModal('privacy-modal'));
  $('btn-terms-link')?.addEventListener('click', () => openModal('terms-modal'));

  // Auth form
  $('auth-form')?.addEventListener('submit', (e) => { e.preventDefault(); sendSignInLink(callbacks); });

  // Create folder
  const createFolder = () => { const name = $('new-folder-name')?.value?.trim(); if (name) createArchivalFolder(name, callbacks); };
  $('btn-create-folder')?.addEventListener('click', createFolder);
  $('new-folder-name')?.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); createFolder(); } });

  $('btn-hamburger')?.addEventListener('click', toggleHamburger);
  $('drawer-backdrop')?.addEventListener('click', toggleHamburger);

  // Categories header is a collapse toggle on mobile (CSS uses the
  // .taxonomy-expanded class on #taxonomy-section). No-op visually on
  // desktop because the grid is always shown there.
  $('btn-taxonomy-collapse')?.addEventListener('click', () => {
    if (window.innerWidth >= 1024) return;
    const section = $('taxonomy-section');
    const toggle  = $('btn-taxonomy-collapse');
    if (!section) return;
    const willExpand = !section.classList.contains('taxonomy-expanded');
    section.classList.toggle('taxonomy-expanded', willExpand);
    toggle?.setAttribute('aria-expanded', willExpand ? 'true' : 'false');
  });

  // Focus-restore: track the last element focused OUTSIDE any modal.
  // When a modal closes, restore focus there so keyboard users don't
  // get stranded at the document body.
  document.addEventListener('focusin', (e) => {
    if (!e.target.closest?.('[role="dialog"], .modal-backdrop, #image-lightbox')) {
      _lastNonModalFocus = e.target;
    }
  }, true);

  document.querySelectorAll('[data-modal-backdrop]').forEach(el => {
    el.addEventListener('click', () => {
      const modalId = el.getAttribute('data-modal-backdrop');
      $(modalId + '-modal').classList.add('hidden');
      restoreFocus();
    });
  });
  document.querySelectorAll('[data-modal-close]').forEach(el => {
    el.addEventListener('click', () => {
      const modalId = el.getAttribute('data-modal-close');
      $(modalId + '-modal').classList.add('hidden');
      restoreFocus();
    });
  });

  // Search: Esc clears query (first press), or blurs if already empty (second press)
  $('search-input')?.addEventListener('keydown', (e) => {
    if (e.key !== 'Escape') return;
    const input = e.currentTarget;
    if (input.value) {
      e.preventDefault();
      e.stopPropagation();
      input.value = '';
      AppState.searchQuery = '';
      invalidateSearchCache();
      refreshContent();
    } else {
      input.blur();
    }
  });

  // Search — only content re-renders (chrome is invariant to the query)
  $('search-input')?.addEventListener('input', debounce((e) => {
    AppState.searchQuery = e.target.value;
    refreshContent();
  }, 300));

  const clearAllFilters = () => {
    AppState.filters = emptyFilters();
    AppState.searchQuery = '';
    AppState.activeFolderId = null;
    AppState.yearRange = { min: 1980, max: 2025 };
    if ($('search-input')) $('search-input').value = '';
    refreshTaxonomy();
    refreshContent();
  };
  $('btn-clear-directory')?.addEventListener('click', clearAllFilters);
  // Empty-state "Clear filters" buttons are rendered dynamically — delegate.
  document.addEventListener('click', (e) => {
    const id = e.target?.id;
    if (id === 'btn-clear-all-filters' || id === 'btn-clear-all-filters-index') clearAllFilters();
  });

  $('btn-clear-folder-filter')?.addEventListener('click', () => {
    AppState.activeFolderId = null;
    refreshContent();
  });

  // --- Orientation ---
  const dismissOrientation = () => {
    const op = $('orientation-panel');
    if (op) op.classList.add('hidden');
    // Hide the "How It Works" section and featured strip header when hero is dismissed
    const how = $('how-it-works');
    const featHead = $('featured-strip-head');
    if (how) how.style.display = 'none';
    if (featHead) featHead.style.display = 'none';
    const whoEl = $('who-section');
    if (whoEl) whoEl.style.display = 'none';
    try { localStorage.setItem('lexicon-orientation-dismissed', 'true'); } catch(e) {}
  };
  $('btn-dismiss-orientation')?.addEventListener('click', dismissOrientation);
  $('btn-close-orientation')?.addEventListener('click', dismissOrientation);
  // "VIEW ALL ENTRIES →" collapses the landing sections and scrolls to grid
  $('btn-hide-featured')?.addEventListener('click', () => {
    dismissOrientation();
    $('image-grid')?.scrollIntoView({ behavior: 'smooth' });
  });

  // Reading mode toggle + TOC scroll spy
  $('btn-reading-mode')?.addEventListener('click', () => {
    const container = $('sticky-note-container');
    const btn = $('btn-reading-mode');
    if (!container) return;
    const isReading = container.classList.toggle('reading-mode');
    if (btn) {
      btn.classList.toggle('active', isReading);
      btn.setAttribute('aria-pressed', String(isReading));
    }
    try { localStorage.setItem('lexicon-reading-mode', isReading ? '1' : '0'); } catch(e) {}
  });
  // Restore reading mode preference
  try {
    if (localStorage.getItem('lexicon-reading-mode') === '1') {
      $('sticky-note-container')?.classList.add('reading-mode');
      const btn = $('btn-reading-mode');
      if (btn) { btn.classList.add('active'); btn.setAttribute('aria-pressed', 'true'); }
    }
  } catch(e) {}

  // TOC scroll-spy: highlight active note section as sidebar scrolls
  const sidebar = $('detail-metadata-sidebar');
  if (sidebar && window.IntersectionObserver) {
    const tocObs = new IntersectionObserver((entries) => {
      entries.forEach(ent => {
        const id = ent.target.id?.replace('note-', '');
        const link = document.querySelector(`.notes-toc-link[data-toc-target="${id}"]`);
        if (link) link.classList.toggle('toc-active', ent.isIntersecting);
      });
    }, { root: sidebar, threshold: 0.3 });
    // Re-observe whenever detail opens (nodes are re-rendered per entry)
    document.addEventListener('lexicon-detail-opened', () => {
      document.querySelectorAll('[id^="note-"]').forEach(el => tocObs.observe(el));
    });
  }

  // --- View Toggles ---
  $('btn-toggle-grid')?.addEventListener('click', () => switchView('grid', callbacks));
  $('btn-toggle-timeline')?.addEventListener('click', () => switchView('timeline', callbacks));

  // Phase 1/2: Visual / Index Mode Toggle
  $('btn-mode-visual')?.addEventListener('click', () => setViewMode('visual'));
  $('btn-mode-index')?.addEventListener('click', () => {
    setViewMode('index');
    renderIndexView(archiveData);
  });

  // Command palette CustomEvents
  document.addEventListener('lexicon-set-view-mode', (e) => {
    setViewMode(e.detail);
    if (e.detail === 'index') renderIndexView(archiveData);
  });
  document.addEventListener('lexicon-kbd-help', showKeyboardHelp);

  // Sort cycle — content-only (sort label is rebuilt inside refreshContent)
  $('btn-sort-cycle')?.addEventListener('click', () => {
    const modes = ['year-desc', 'year-asc', 'brand-az', 'default'];
    const idx = modes.indexOf(AppState.sortMode || 'year-desc');
    AppState.sortMode = modes[(idx + 1) % modes.length];
    try { localStorage.setItem('lexicon.sort-mode', AppState.sortMode); } catch(e) {}
    refreshContent();
  });

  // Detail
  $('btn-back-grid')?.addEventListener('click', () => closeDetail(callbacks, archiveData));
  $('btn-back-grid-mobile')?.addEventListener('click', () => closeDetail(callbacks, archiveData));
  $('btn-toggle-hotspots-mobile')?.addEventListener('click', toggleMobileHotspots);
  function openNexus() {
    if (!AppState.selectedEntryId) return;
    openConnectionMatrix(AppState.selectedEntryId, archiveData, callbacks);
    const matrix = $('connection-matrix');
    if (matrix && !matrix.classList.contains('hidden')) {
      const closeBtn = $('btn-close-matrix');
      if (closeBtn) requestAnimationFrame(() => closeBtn.focus());
      trapFocus(matrix);
    }
  }
  $('btn-nexus-mobile')?.addEventListener('click', openNexus);
  $('btn-related-open-nexus')?.addEventListener('click', openNexus);
  $('btn-notes-mobile')?.addEventListener('click', () => openMobileNotes());
  $('btn-close-mobile-notes')?.addEventListener('click', () => $('mobile-notes-sheet')?.classList.add('hidden'));
  document.querySelectorAll('.mobile-note-tab').forEach(tab => {
    tab.addEventListener('click', () => showMobileNote(tab.dataset.mobileNote));
  });
  $('btn-viewer-prev')?.addEventListener('click', () => navigateEntry(-1, archiveData, callbacks));
  $('btn-viewer-next')?.addEventListener('click', () => navigateEntry(1, archiveData, callbacks));

  $('btn-bookmark-entry')?.addEventListener('click', () => {
    if (AppState.selectedEntryId) toggleBookmark(AppState.selectedEntryId, callbacks);
  });

  $('btn-copy-link')?.addEventListener('click', () => {
    const lang = AppState.language;
    const btn = $('btn-copy-link');
    const url = `${window.location.origin}${window.location.pathname}#detail/${AppState.selectedEntryId}/${AppState.currentImageIndex}`;
    const flashCopied = () => {
      if (!btn) return;
      const original = btn.textContent;
      btn.textContent = '✓ ' + getTranslation('link_copied', lang).replace('.','').toUpperCase();
      btn.classList.add('btn-copied');
      showToast(getTranslation('link_copied', lang));
      setTimeout(() => {
        btn.textContent = original;
        btn.classList.remove('btn-copied');
      }, 1500);
    };
    navigator.clipboard?.writeText(url).then(flashCopied).catch(() => {
      showToast(url);
    });
  });

  function openCmdPalette() {
    toggleCmdPalette(archiveData, callbacks);
    const pal = $('cmd-palette');
    if (pal && !pal.classList.contains('hidden')) trapFocus(pal);
  }
  $('btn-cmd-palette-hint')?.addEventListener('click', openCmdPalette);
  $('btn-hero-search')?.addEventListener('click', openCmdPalette);

  // Cite Entry modal: build BibTeX + Chicago + permalink for the active entry
  $('btn-cite-entry')?.addEventListener('click', () => openCiteModal());
  document.querySelectorAll('.cite-copy-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const which = btn.dataset.citeCopy;
      const el = $('cite-' + which);
      if (!el) return;
      navigator.clipboard?.writeText(el.textContent).then(() => {
        const original = btn.textContent;
        btn.textContent = '✓ Copied';
        btn.classList.add('btn-copied');
        showToast(getTranslation('link_copied', AppState.language));
        setTimeout(() => { btn.textContent = original; btn.classList.remove('btn-copied'); }, 1400);
      });
    });
  });

  // Lightbox: click the detail image to open zoomable fullscreen view
  $('detail-image')?.addEventListener('click', () => openLightbox());
  $('btn-close-lightbox')?.addEventListener('click', () => closeLightbox());
  $('btn-lightbox-prev')?.addEventListener('click', () => navigateLightbox(-1));
  $('btn-lightbox-next')?.addEventListener('click', () => navigateLightbox(1));
  $('lightbox-stage')?.addEventListener('click', (e) => {
    // Suppress click-to-zoom and click-to-close while a pinch zoom is
    // active so a fingers-up touchend doesn't synthesise a stray click.
    if (_lightboxZoomed && _pinchState) return;
    if (e.target.id === 'lightbox-stage') { closeLightbox(); return; }
    toggleLightboxZoom(e);
  });

  // Click-to-filter from detail metadata grid: tap any tag → filter archive
  $('metadata-grid')?.addEventListener('click', (e) => {
    const btn = e.target.closest('.metadata-tag-btn');
    if (!btn) return;
    const type  = btn.dataset.taxType;
    const value = btn.dataset.taxValue;
    if (!type || !value) return;
    // Toggle this tag value within its axis (multi-select); keep other axes.
    const current = AppState.filters[type] || '';
    const activeVals = current.split('|').map(s => s.trim()).filter(Boolean);
    const idx = activeVals.indexOf(value);
    if (idx >= 0) { activeVals.splice(idx, 1); } else { activeVals.push(value); }
    AppState.filters[type] = activeVals.length ? activeVals.join('|') : null;
    closeDetail(callbacks, archiveData);
    // switchView's onUpdate already calls refreshUI; just refresh the
    // category cells to reflect the new active filter.
    switchView('grid', callbacks);
    refreshTaxonomy();
    showToast(getTranslation('filtering_label', AppState.language) + ' ' + value);
  });

  $('btn-open-matrix')?.addEventListener('click', openNexus);
  $('btn-close-matrix')?.addEventListener('click', () => { closeConnectionMatrix(); restoreFocus(); });
  $('matrix-backdrop')?.addEventListener('click', () => { closeConnectionMatrix(); restoreFocus(); });

  $('btn-save-to-folder')?.addEventListener('click', () => {
    if (!currentUser) { showToast(getTranslation('auth_required', AppState.language)); toggleAuth(); return; }
    openModal('save-folder-modal');
    renderSaveFolderModal();
  });
  $('btn-save-folder-mobile')?.addEventListener('click', () => {
    if (!currentUser) { showToast(getTranslation('auth_required', AppState.language)); toggleAuth(); return; }
    openModal('save-folder-modal');
    renderSaveFolderModal();
  });

  $('btn-export-all-folders')?.addEventListener('click', () => exportAllFolders());

  // Hotspot interaction is now handled in render-detail.js per-render.


  // Keyboard
  window.addEventListener('keydown', (e) => {
    // Lightbox takes priority — Esc closes it, arrows navigate inside it
    const lightbox = $('image-lightbox');
    if (lightbox && !lightbox.classList.contains('hidden')) {
      if (e.key === 'Escape')     { e.preventDefault(); closeLightbox(); return; }
      if (e.key === 'ArrowLeft')  { e.preventDefault(); navigateLightbox(-1); return; }
      if (e.key === 'ArrowRight') { e.preventDefault(); navigateLightbox(1); return; }
    }
    // Generic: Escape closes any open dialog-style modal
    if (e.key === 'Escape') {
      // Connection matrix needs its own close path for body overflow cleanup
      const matrix = $('connection-matrix');
      if (matrix && !matrix.classList.contains('hidden')) {
        closeConnectionMatrix(); restoreFocus(); e.preventDefault(); return;
      }
      const openModal = document.querySelector('[role="dialog"]:not(.hidden):not(#image-lightbox)');
      if (openModal) {
        openModal.classList.add('hidden');
        restoreFocus();
        e.preventDefault();
        return;
      }
    }
    // Don't swallow typing in form fields
    const tag = document.activeElement?.tagName;
    if (tag === 'INPUT' || tag === 'TEXTAREA' || document.activeElement?.isContentEditable) return;
    if (AppState.selectedEntryId) {
      if (e.key === 'ArrowLeft')       { e.preventDefault(); navigateEntry(-1, archiveData, callbacks); }
      else if (e.key === 'ArrowRight') { e.preventDefault(); navigateEntry(1, archiveData, callbacks); }
      else if (e.key === 'Escape')     closeDetail(callbacks, archiveData);
    }
    // Grid cell keyboard activation
    if ((e.key === 'Enter' || e.key === ' ') && document.activeElement?.classList.contains('grid-cell')) {
      e.preventDefault();
      const id  = document.activeElement.dataset.entryId;
      const idx = document.activeElement.dataset.imgIndex || 0;
      if (id) window.location.hash = `detail/${id}/${idx}`;
    }
    // Entry-item (A-Z compact list) keyboard activation
    if ((e.key === 'Enter' || e.key === ' ') && document.activeElement?.classList.contains('entry-item')) {
      e.preventDefault();
      const id = document.activeElement.dataset.id;
      if (id) window.location.hash = `detail/${id}/0`;
    }
    // Phase 1/2 Keyboard Shortcuts
    if (e.key === '?') {
      e.preventDefault();
      showKeyboardHelp();
    }
    if (e.key === '/') {
      e.preventDefault();
      const searchInput = $('search-input');
      if (searchInput) searchInput.focus();
    }
    if (e.key === 'v' || e.key === 'V') {
      e.preventDefault();
      setViewMode('visual');
    }
    if (e.key === 'i' || e.key === 'I') {
      e.preventDefault();
      setViewMode('index');
      renderIndexView(archiveData);
    }
    if (e.key === 'r' || e.key === 'R') {
      const container = $('sticky-note-container');
      const btn = $('btn-reading-mode');
      if (container && !e.metaKey && !e.ctrlKey) {
        e.preventDefault();
        const isReading = container.classList.toggle('reading-mode');
        if (btn) { btn.classList.toggle('active', isReading); btn.setAttribute('aria-pressed', String(isReading)); }
        try { localStorage.setItem('lexicon-reading-mode', isReading ? '1' : '0'); } catch(ex) {}
      }
    }
    if ((e.key === 'n' || e.key === 'N') && AppState.selectedEntryId && !e.metaKey && !e.ctrlKey) {
      e.preventDefault();
      openNexus();
    }
    if ((e.key === 'p' || e.key === 'P') && AppState.selectedEntryId && !e.metaKey && !e.ctrlKey) {
      e.preventDefault();
      $('btn-copy-link')?.click();
    }
    // Brutalist Index View: j/k row navigation when index mode is active
    if (AppState.viewMode === 'index') {
      if (e.key === 'j' || e.key === 'ArrowDown') {
        e.preventDefault();
        indexNavigateRow(1);
      } else if (e.key === 'k' || e.key === 'ArrowUp') {
        e.preventDefault();
        indexNavigateRow(-1);
      } else if (e.key === 'Enter') {
        e.preventDefault();
        indexActivateRow();
      } else if ((e.key === 's' || e.key === 'S') && !e.metaKey && !e.ctrlKey) {
        // Save focused row entry to folder
        const focusedRow = document.querySelector('#index-table-view tbody tr.focused');
        if (focusedRow?.dataset.entryId) {
          e.preventDefault();
          AppState.selectedEntryId = focusedRow.dataset.entryId;
          callbacks.renderFolderOptions?.();
        }
      } else if (e.key === 'c' || e.key === 'C') {
        // Cite focused row entry
        const focusedRow = document.querySelector('#index-table-view tbody tr.focused');
        if (focusedRow?.dataset.entryId) {
          e.preventDefault();
          AppState.selectedEntryId = focusedRow.dataset.entryId;
          openCiteModal();
        }
      }
    }
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
      e.preventDefault();
      openCmdPalette();
    }
    handleCmdKeydown(e, archiveData, callbacks);
  });

  $('cmd-input')?.addEventListener('input', (e) => {
    renderCmdResults(e.target.value, archiveData, callbacks);
  });
  $('cmd-palette-backdrop')?.addEventListener('click', () => toggleCmdPalette(archiveData, callbacks));

  // Cookie Banner (GDPR compliance) — show until the user makes any choice
  var cookieChoice;
  try { cookieChoice = localStorage.getItem('lexicon-terms-accepted'); } catch(e) {}
  if (!cookieChoice) {
    $('cookie-banner')?.classList.remove('hidden');
  }
  // Populate cookie notice text from translations
  const cookieNotice = $('cookie-notice-text');
  if (cookieNotice) {
    cookieNotice.textContent = getTranslation('cookie_notice', AppState.language);
  }
  $('btn-accept-cookies')?.addEventListener('click', () => {
    try { localStorage.setItem('lexicon-terms-accepted', 'true'); } catch(e) {}
    $('cookie-banner')?.classList.add('hidden');
  });
  $('btn-reject-cookies')?.addEventListener('click', () => {
    try { localStorage.setItem('lexicon-terms-accepted', 'rejected'); } catch(e) {}
    $('cookie-banner')?.classList.add('hidden');
  });

  // Custom Refresh Event
  document.addEventListener('lexicon-refresh', refreshUI);

  // ── Mobile bottom-sheet filter ──
  const openMobileSheet = () => {
    const sheet = $('mobile-filter-sheet');
    if (!sheet) return;
    sheet.classList.remove('hidden');
    document.body.style.overflow = 'hidden';
    syncMobileSheetChips();
    syncYearRangeSlider();
    updateMobileSheetUrl();
    updateMbsResultCount();
    const closeBtn = $('btn-mobile-filter-close');
    if (closeBtn) requestAnimationFrame(() => closeBtn.focus());
    trapFocus(sheet);
  };
  const closeMobileSheet = () => {
    const sheet = $('mobile-filter-sheet');
    if (sheet) sheet.classList.add('hidden');
    document.body.style.overflow = '';
    restoreFocus();
  };

  $('btn-mobile-filter')?.addEventListener('click', openMobileSheet);
  $('btn-mobile-filter-close')?.addEventListener('click', closeMobileSheet);
  $('mobile-sheet-backdrop')?.addEventListener('click', closeMobileSheet);

  // Chip toggle in bottom sheet
  document.querySelectorAll('.mbs-chip').forEach(chip => {
    chip.addEventListener('click', () => {
      const filterKey = chip.dataset.mbsFilter;
      const val = chip.dataset.mbsVal;
      const current = AppState.filters[filterKey] || '';
      const activeVals = current.split('|').map(s => s.trim()).filter(Boolean);
      const idx = activeVals.indexOf(val);
      if (idx >= 0) { activeVals.splice(idx, 1); } else { activeVals.push(val); }
      AppState.filters[filterKey] = activeVals.length ? activeVals.join('|') : null;
      syncMobileSheetChips();
      updateMobileSheetUrl();
      updateMbsResultCount();
    });
  });

  $('btn-mbs-clear')?.addEventListener('click', () => {
    AppState.filters = emptyFilters();
    AppState.yearRange = { min: 1980, max: 2025 };
    syncMobileSheetChips();
    syncYearRangeSlider();
    updateMobileSheetUrl();
    updateMbsResultCount();
  });

  $('btn-mbs-apply')?.addEventListener('click', () => {
    closeMobileSheet();
    invalidateSearchCache();
    refreshContent();
    updateHash('grid');
  });

  // Year range dual-thumb slider
  const minInput = $('mbs-year-min');
  const maxInput = $('mbs-year-max');
  function updateYearRangeUI() {
    if (!minInput || !maxInput) return;
    const mn = parseInt(minInput.value);
    const mx = parseInt(maxInput.value);
    const span = 2025 - 1980;
    const fill = $('mbs-year-fill');
    if (fill) {
      fill.style.left  = ((mn - 1980) / span * 100) + '%';
      fill.style.right = ((2025 - mx)  / span * 100) + '%';
    }
    const label = $('mbs-year-label');
    if (label) label.textContent = (mn === 1980 && mx === 2025) ? 'ALL' : `${mn}–${mx}`;
    AppState.yearRange = { min: mn, max: mx };
    invalidateSearchCache();
    updateMobileSheetUrl();
    updateMbsResultCount();
  }
  minInput?.addEventListener('input', () => {
    if (parseInt(minInput.value) >= parseInt(maxInput.value)) minInput.value = parseInt(maxInput.value) - 1;
    updateYearRangeUI();
  });
  maxInput?.addEventListener('input', () => {
    if (parseInt(maxInput.value) <= parseInt(minInput.value)) maxInput.value = parseInt(minInput.value) + 1;
    updateYearRangeUI();
  });
}

// ── Mobile bottom-sheet helpers ──────────────────────────────────────
function syncMobileSheetChips() {
  document.querySelectorAll('.mbs-chip').forEach(chip => {
    const filterKey = chip.dataset.mbsFilter;
    const val = chip.dataset.mbsVal;
    const current = AppState.filters[filterKey] || '';
    const activeVals = current.split('|').map(s => s.trim()).filter(Boolean);
    const isActive = activeVals.includes(val);
    chip.classList.toggle('active', isActive);
    chip.setAttribute('aria-pressed', String(isActive));
  });
  // Update the mobile filter badge count (includes year range if active)
  const tagTotal = Object.values(AppState.filters).filter(Boolean)
    .flatMap(v => v.split('|').filter(Boolean)).length;
  const yr = AppState.yearRange || { min: 1980, max: 2025 };
  const yearActive = yr.min > 1980 || yr.max < 2025 ? 1 : 0;
  const total = tagTotal + yearActive;
  const badge = $('mobile-filter-count');
  if (badge) {
    badge.textContent = total;
    badge.classList.toggle('hidden', total === 0);
  }
}

function syncYearRangeSlider() {
  const minInput = $('mbs-year-min');
  const maxInput = $('mbs-year-max');
  if (!minInput || !maxInput) return;
  const { min, max } = AppState.yearRange || { min: 1980, max: 2025 };
  minInput.value = min;
  maxInput.value = max;
  const span = 2025 - 1980;
  const fill = $('mbs-year-fill');
  if (fill) {
    fill.style.left  = ((min - 1980) / span * 100) + '%';
    fill.style.right = ((2025 - max)  / span * 100) + '%';
  }
  const label = $('mbs-year-label');
  if (label) label.textContent = (min === 1980 && max === 2025) ? 'ALL' : `${min}–${max}`;
}

function updateMobileSheetUrl() {
  const urlEl = $('mbs-shareable-url');
  if (!urlEl) return;
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(AppState.filters)) {
    if (v) params.set(k, v);
  }
  const yr = AppState.yearRange || { min: 1980, max: 2025 };
  if (yr.min > 1980) params.set('y_min', yr.min);
  if (yr.max < 2025) params.set('y_max', yr.max);
  const qs = params.toString();
  urlEl.textContent = qs ? `/archive?${qs}` : '—';
}

function updateMbsResultCount() {
  const countEl = $('mbs-result-count');
  if (!countEl || !archiveData) return;
  countEl.textContent = `· ${getFilteredEntries(archiveData).length} RESULTS`;
}

// ── HERO (Phase 1 — populates right column with featured entry) ──
function renderHero(archiveData) {
  // Update live stats
  const statEl = $('stat-entries');
  if (statEl) statEl.textContent = archiveData.length.toLocaleString();
  const statBrands = $('stat-brands');
  if (statBrands) {
    const uniqueBrands = new Set(archiveData.map(e => e.tags?.brand).filter(Boolean));
    statBrands.textContent = uniqueBrands.size.toLocaleString();
  }
  const statMov = $('stat-movements');
  if (statMov) {
    const uniqueMovements = new Set(archiveData.flatMap(e => (e.tags?.theories || '').split('|').map(s => s.trim())).filter(Boolean));
    statMov.textContent = uniqueMovements.size.toLocaleString();
  }

  // Always reveal the featured strip header, "How It Works", and "Who It's For"
  const featHead = $('featured-strip-head');
  const how = $('how-it-works');
  const who = $('who-section');
  if (featHead) featHead.style.display = 'flex';
  if (how) how.style.display = 'block';
  if (who) who.style.display = 'block';

  const panel = $('orientation-panel');
  if (!panel || panel.classList.contains('hidden')) return;

  const tagLabelMap = {
    corporeal: 'Corporeal Intervention', critique: 'Institutional Critique',
    subculture: 'Subcultural Codification', semiotic: 'Semiotic Sabotage',
    strategy: 'Strategic Appropriation', provenance: 'Historical Lineage',
  };

  // Pick one entry per category (most recent), up to 4 candidates
  const HERO_CATS = ['corporeal', 'critique', 'subculture', 'semiotic'];
  const sorted = [...archiveData].sort((a, b) => (b.year || 0) - (a.year || 0));
  const picks = HERO_CATS.map(cat =>
    sorted.find(e => getTagCategory(e.tags?.politics || '') === cat && (e.notes?.critique || e.notes?.provenance))
  ).filter(Boolean);
  // Fallback: use most recent entries with any notes
  if (picks.length < 2) {
    sorted.filter(e => (e.notes?.critique || e.notes?.provenance)).slice(0, 4).forEach(e => {
      if (!picks.includes(e)) picks.push(e);
    });
  }

  if (picks.length === 0) return;

  let heroIndex = 0;

  function showHeroEntry(idx) {
    const candidate = picks[idx];
    if (!candidate) return;
    const cat = getTagCategory(candidate.tags?.politics || '');
    const tagLabel = tagLabelMap[cat] || 'Analytical Record';
    const brand = (candidate.tags?.brand || '').toUpperCase();
    const year = candidate.year || '—';
    const season = candidate.season ? candidate.season.toUpperCase() : 'ARCHIVE';
    const hook = candidate.notes?.critique
      ? candidate.notes.critique.replace(/<[^>]+>/g, '').slice(0, 200) + '…'
      : candidate.notes?.provenance
        ? candidate.notes.provenance.replace(/<[^>]+>/g, '').slice(0, 200) + '…'
        : '';

    const tagEl = $('hero-tag-label');
    if (tagEl) {
      tagEl.textContent = tagLabel.toUpperCase();
      tagEl.style.borderColor = `var(--c-${cat})`;
      tagEl.style.color = `var(--c-${cat})`;
    }

    const titleEl = $('hero-featured-title');
    if (titleEl && candidate.title) titleEl.innerHTML = `<em>${candidate.title}</em>`;

    const brandEl = $('hero-featured-brand');
    if (brandEl) brandEl.textContent = `${brand} · ${year} · ${season}`;

    const descEl = $('hero-featured-desc');
    if (descEl) descEl.textContent = hook;

    const idSpan = panel.querySelector('.hero-id');
    if (idSpan) idSpan.textContent = `N-${candidate.id.slice(0, 4).toUpperCase()}`;

    // Update dot indicators
    const dotsEl = panel.querySelector('.hero-dots');
    if (dotsEl) {
      const needed = picks.length;
      const existing = dotsEl.querySelectorAll('.hero-dot');
      // Rebuild if count changed
      if (existing.length !== needed) {
        dotsEl.innerHTML = picks.map((_, i) =>
          `<button class="hero-dot${i === idx ? ' active' : ''}" data-hero-idx="${i}" aria-label="Featured entry ${i + 1}" aria-pressed="${i === idx}"></button>`
        ).join('');
        dotsEl.querySelectorAll('.hero-dot').forEach(dotBtn => {
          dotBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            heroIndex = parseInt(dotBtn.dataset.heroIdx, 10);
            showHeroEntry(heroIndex);
          });
        });
      } else {
        existing.forEach((d, i) => {
          d.classList.toggle('active', i === idx);
          d.setAttribute('aria-pressed', String(i === idx));
        });
      }
    }

    // Make the right column clickable to open the entry
    const rightCol = $('hero-featured-slot');
    if (rightCol) {
      rightCol.style.cursor = 'pointer';
      rightCol.onclick = () => { window.location.hash = `detail/${candidate.id}/0`; };
    }
  }

  showHeroEntry(0);

  // Auto-rotate every 6 seconds if prefers-reduced-motion is not set
  if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches && picks.length > 1) {
    let heroTimer = setInterval(() => {
      if ($('orientation-panel')?.classList.contains('hidden')) {
        clearInterval(heroTimer);
        return;
      }
      heroIndex = (heroIndex + 1) % picks.length;
      showHeroEntry(heroIndex);
    }, 6000);
  }
}

// ── CITATIONS (Phase 3 — multi-format export) ──
function openCiteModal() {
  const entry = archiveData.find(e => e.id === AppState.selectedEntryId);
  if (!entry) return;
  const modal = $('cite-modal');
  if (!modal) return;

  const url   = `${window.location.origin}${window.location.pathname}#detail/${entry.id}/0`;
  const brand = entry.tags?.brand || entry.id;
  const year  = entry.year || '';
  const season = entry.season ? entry.season + ' ' : '';
  const collectionTitle = entry.title
    ? entry.title
    : `${brand} ${season}${year}`.trim();
  const subtitle = entry.subtitle ? `: ${entry.subtitle}` : '';
  const fullTitle = collectionTitle + subtitle;
  const accessDate = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  const accessIso = new Date().toISOString().slice(0, 10);
  const siteName = 'THE LEXICON: Forensic Archive of Visual Culture';

  // Chicago Manual of Style 17th ed. note format
  const chicago =
    `"${fullTitle}," ${siteName}, accessed ${accessDate}, ${url}.`;

  // MLA 9th edition
  const mla =
    `"${fullTitle}." ${siteName}, ${year}, ${url}. Accessed ${accessDate}.`;

  // APA 7th edition
  const apa =
    `${siteName}. (${year}). ${fullTitle}. Retrieved ${accessDate}, from ${url}`;

  // Harvard
  const harvard =
    `${siteName} (${year}) ${fullTitle}. Available at: ${url} (Accessed: ${accessDate}).`;

  // BibTeX @misc with stable citekey
  const citekey = `lexicon-${entry.id}`;
  const bibtex =
    `@misc{${citekey},\n` +
    `  title        = {{${fullTitle.replace(/[{}]/g,'')}}},\n` +
    `  howpublished = {{${siteName}}},\n` +
    `  year         = {${year}},\n` +
    `  urldate      = {${accessIso}},\n` +
    `  note         = {Entry ID: ${entry.id}. Accessed ${accessDate}.},\n` +
    `  url          = {${url}}\n` +
    `}`;

  if ($('cite-chicago')) $('cite-chicago').textContent = chicago;
  if ($('cite-mla'))     $('cite-mla').textContent     = mla;
  if ($('cite-apa'))     $('cite-apa').textContent     = apa;
  if ($('cite-harvard')) $('cite-harvard').textContent = harvard;
  if ($('cite-bibtex'))  $('cite-bibtex').textContent  = bibtex;
  if ($('cite-url'))     $('cite-url').textContent     = url;

  modal.classList.remove('hidden');
  modal.querySelector('[data-modal-close]')?.focus();
  trapFocus(modal);
}

// ── KEYBOARD SHORTCUTS HELP ──
function showKeyboardHelp() {
  const modal = $('kbd-help-modal');
  if (!modal) return;
  modal.classList.remove('hidden');
  modal.querySelector('[data-modal-close]')?.focus();
  trapFocus(modal);
}

// ── FOCUS RESTORE ──
// Last element focused outside any modal — updated by focusin listener
// in setupEventListeners(). restoreFocus() returns focus there after a
// modal/lightbox closes so keyboard users don't lose their place.
let _lastNonModalFocus = null;
function restoreFocus() {
  if (_lastNonModalFocus && document.body.contains(_lastNonModalFocus)) {
    try { _lastNonModalFocus.focus(); } catch (e) { /* element no longer focusable */ }
  }
}

// ── FOCUS TRAP ──
// Constrain keyboard focus inside a modal element while it's open.
// Call trapFocus(el) when opening; listener is removed automatically when
// the element gains 'hidden' class (via MutationObserver).
function trapFocus(modal) {
  function getFocusable() { return [...modal.querySelectorAll(FOCUSABLE_SELECTORS)].filter(el => !el.closest('[hidden]') && el.offsetParent !== null); }
  function handler(e) {
    if (e.key !== 'Tab') return;
    const focusable = getFocusable();
    if (!focusable.length) { e.preventDefault(); return; }
    const first = focusable[0];
    const last  = focusable[focusable.length - 1];
    if (e.shiftKey) {
      if (document.activeElement === first) { e.preventDefault(); last.focus(); }
    } else {
      if (document.activeElement === last)  { e.preventDefault(); first.focus(); }
    }
  }
  modal.addEventListener('keydown', handler);
  // Auto-remove when modal is hidden
  const obs = new MutationObserver(() => {
    if (modal.classList.contains('hidden')) {
      modal.removeEventListener('keydown', handler);
      obs.disconnect();
    }
  });
  obs.observe(modal, { attributes: true, attributeFilter: ['class'] });
}

// ── LIGHTBOX ──
let _lightboxZoomed = false;
let _pinchState = null; // { startDist, startScale, startCenter, currentScale, currentX, currentY }
let _pinchHandlersBound = false;

function openLightbox() {
  const entry = archiveData.find(e => e.id === AppState.selectedEntryId);
  if (!entry || !entry.images?.length) return;
  const box = $('image-lightbox');
  if (!box) return;
  box.classList.remove('hidden');
  document.body.style.overflow = 'hidden';
  _lightboxZoomed = false;
  renderLightbox();
  // Focus the close button so keyboard users have a home base.
  const closeBtn = $('btn-close-lightbox');
  if (closeBtn) requestAnimationFrame(() => closeBtn.focus());
  trapFocus(box);
  // Pinch handlers are bound once and persist across opens.
  if (!_pinchHandlersBound) bindLightboxPinch();
}
function closeLightbox() {
  const box = $('image-lightbox');
  if (!box) return;
  box.classList.add('hidden');
  document.body.style.overflow = '';
  const img = $('lightbox-image');
  if (img) {
    img.style.transform = '';
    img.style.cursor = '';
    img.style.transformOrigin = '';
  }
  _lightboxZoomed = false;
  _pinchState = null;
  restoreFocus();
}

/** Two-finger pinch-zoom + pan inside the lightbox.
 *  Single-tap stage still closes (handled elsewhere); double-tap on the
 *  image resets to 1x. Range: 1x to 5x. */
function bindLightboxPinch() {
  const stage = $('lightbox-stage');
  const img   = $('lightbox-image');
  if (!stage || !img) return;
  _pinchHandlersBound = true;

  const getDistance = (touches) => {
    const dx = touches[0].clientX - touches[1].clientX;
    const dy = touches[0].clientY - touches[1].clientY;
    return Math.hypot(dx, dy);
  };
  const getCenter = (touches) => ({
    x: (touches[0].clientX + touches[1].clientX) / 2,
    y: (touches[0].clientY + touches[1].clientY) / 2,
  });

  stage.addEventListener('touchstart', (e) => {
    if (e.touches.length === 2) {
      e.preventDefault();
      _pinchState = {
        startDist: getDistance(e.touches),
        startScale: _pinchState?.currentScale || 1,
        currentScale: _pinchState?.currentScale || 1,
        startCenter: getCenter(e.touches),
        currentX: _pinchState?.currentX || 0,
        currentY: _pinchState?.currentY || 0,
      };
    }
  }, { passive: false });

  stage.addEventListener('touchmove', (e) => {
    if (e.touches.length === 2 && _pinchState) {
      e.preventDefault();
      const newDist = getDistance(e.touches);
      const scale = Math.min(5, Math.max(1, _pinchState.startScale * (newDist / _pinchState.startDist)));
      _pinchState.currentScale = scale;
      img.style.transformOrigin = '50% 50%';
      img.style.transform = `translate(${_pinchState.currentX}px, ${_pinchState.currentY}px) scale(${scale})`;
      img.style.transition = 'none';
      _lightboxZoomed = scale > 1.05;
    } else if (e.touches.length === 1 && _pinchState && _pinchState.currentScale > 1.05) {
      // Single-finger pan while zoomed
      e.preventDefault();
    }
  }, { passive: false });

  stage.addEventListener('touchend', (e) => {
    if (e.touches.length === 0 && _pinchState && _pinchState.currentScale <= 1.05) {
      // Snapped back to 1x — fully reset
      img.style.transform = '';
      img.style.transition = 'transform 0.2s ease';
      _pinchState = null;
      _lightboxZoomed = false;
    }
  }, { passive: true });

  // Double-tap to reset zoom (mobile equivalent of click-to-zoom-out)
  let lastTap = 0;
  img.addEventListener('touchend', (e) => {
    const now = Date.now();
    if (now - lastTap < 300 && _lightboxZoomed) {
      e.preventDefault();
      img.style.transform = '';
      img.style.transition = 'transform 0.2s ease';
      _pinchState = null;
      _lightboxZoomed = false;
    }
    lastTap = now;
  }, { passive: false });
}
function renderLightbox() {
  const entry = archiveData.find(e => e.id === AppState.selectedEntryId);
  if (!entry) return;
  const idx = AppState.currentImageIndex;
  const imgs = entry.images || [];
  const current = imgs[idx];
  if (!current) return;
  const img = $('lightbox-image');
  const webp = $('lightbox-image-webp');
  const counter = $('lightbox-counter');
  if (img) {
    if (webp) webp.srcset = resolveImgSrc({ src: webpSrc(current) });
    img.src = resolveImgSrc(current);
    img.alt = getTranslation(entry.title || entry.id, AppState.language);
    img.style.transform = '';
  }
  if (counter) counter.textContent = (idx + 1) + ' / ' + imgs.length;
  _lightboxZoomed = false;
  $('lightbox-stage').style.cursor = 'zoom-in';
}
function navigateLightbox(direction) {
  const entry = archiveData.find(e => e.id === AppState.selectedEntryId);
  if (!entry) return;
  const imgs = entry.images || [];
  if (imgs.length <= 1) return;
  let next = AppState.currentImageIndex + direction;
  if (next < 0) next = imgs.length - 1;
  if (next >= imgs.length) next = 0;
  AppState.currentImageIndex = next;
  renderLightbox();
}
function toggleLightboxZoom(e) {
  const img = $('lightbox-image');
  const stage = $('lightbox-stage');
  if (!img || !stage) return;
  if (_lightboxZoomed) {
    img.style.transform = '';
    stage.style.cursor = 'zoom-in';
    _lightboxZoomed = false;
  } else {
    // Zoom 2.5× toward click point
    const rect = img.getBoundingClientRect();
    const offsetX = e.clientX - rect.left;
    const offsetY = e.clientY - rect.top;
    const originX = (offsetX / rect.width) * 100;
    const originY = (offsetY / rect.height) * 100;
    img.style.transformOrigin = `${originX}% ${originY}%`;
    img.style.transform = 'scale(2.5)';
    stage.style.cursor = 'zoom-out';
    _lightboxZoomed = true;
  }
}

function openMobileNotes() {
  const sheet = $('mobile-notes-sheet');
  if (!sheet) return;
  sheet.classList.remove('hidden');
  // Default to provenance tab
  showMobileNote('provenance');
}

function showMobileNote(type) {
  const entry = archiveData.find(e => e.id === AppState.selectedEntryId);
  if (!entry || !entry.notes) return;
  const lang = AppState.language;
  const labels = {
    provenance: getTranslation('note_provenance', lang),
    critique:   getTranslation('note_critique', lang),
    strategy:   getTranslation('note_strategy', lang)
  };
  const colors = {
    provenance: { bg: '#E6FF00', fg: '#000' },
    critique:   { bg: '#FF0000', fg: '#fff' },
    strategy:   { bg: '#0000FF', fg: '#fff' }
  };
  let raw = entry.notes[type] || '';
  let text = getTranslation(raw, lang).replace(/\[cite:\s*\d+\]/g, '').replace(/—/g, ' —').replace(/--/g, ' —').trim();
  const titleEl = $('mobile-notes-title');
  const bodyEl  = $('mobile-notes-body');
  if (titleEl) {
    titleEl.textContent = labels[type] || type.toUpperCase();
    const hdr = titleEl.parentElement;
    if (hdr && colors[type]) {
      hdr.style.background = colors[type].bg;
      hdr.style.color      = colors[type].fg;
    }
  }
  if (bodyEl) bodyEl.textContent = text || '—';
  // Visual active state on tabs
  document.querySelectorAll('.mobile-note-tab').forEach(t => {
    if (t.dataset.mobileNote === type) {
      t.style.background = colors[type].bg;
      t.style.color      = colors[type].fg;
    } else {
      t.style.background = '';
      t.style.color      = '';
    }
  });
}

function toggleHamburger() {
  const panel    = $('index-panel');
  const backdrop = $('drawer-backdrop');
  const btn      = $('btn-hamburger');
  if (!panel || !backdrop || !btn) return;
  const isOpen = panel.classList.contains('translate-x-0');
  if (isOpen) {
    panel.classList.remove('translate-x-0');
    panel.classList.add('-translate-x-full');
    backdrop.classList.add('hidden');
    btn.setAttribute('aria-expanded', 'false');
    document.body.style.overflow = '';
  } else {
    panel.classList.add('translate-x-0');
    panel.classList.remove('-translate-x-full');
    backdrop.classList.remove('hidden');
    btn.setAttribute('aria-expanded', 'true');
    // Prevent body scroll behind the mobile drawer; desktop is unaffected
    // because the drawer transform is a no-op at lg breakpoint.
    if (window.innerWidth < 1024) document.body.style.overflow = 'hidden';
    // Drawer was just opened on mobile — re-render the entry list it
    // skipped while hidden (see render-grid.js renderEntryList guard).
    if (window.innerWidth < 1024) document.dispatchEvent(new CustomEvent('lexicon-refresh'));
  }
}

function toggleTheme() {
  const isDark = document.documentElement.classList.toggle('dark');
  try { localStorage.setItem('lexicon-theme', isDark ? 'dark' : 'light'); } catch(e) {}
  // Reflect theme in <meta name="theme-color"> so mobile chrome matches.
  const meta = document.querySelector('meta[name="theme-color"]');
  if (meta) meta.setAttribute('content', isDark ? '#000000' : '#FDFCF0');
  showToast(isDark ? 'Dark mode' : 'Light mode');
  refreshUI();
}

const LANG_DISPLAY = {
  'en':    'English',
  'en-gb': 'English (GB)',
  'en-us': 'English (US)',
  'fr':    'Français',
  'it':    'Italiano',
  'es':    'Español',
  'de':    'Deutsch',
  'pt':    'Português',
  'ru':    'Русский',
  'zh':    '中文',
  'ja':    '日本語',
  'ko':    '한국어'
};

function renderLangDropdown() {
  const dd = $('lang-dropdown');
  if (!dd) return;
  dd.innerHTML = supportedLanguages.map(code => {
    const name = LANG_DISPLAY[code] || code.toUpperCase();
    const isActive = code === AppState.language;
    const activeClass = isActive ? 'bg-black text-white dark:bg-acid dark:text-black' : 'hover:bg-black/10 dark:hover:bg-white/10';
    // ARIA spec: role="option" must be a direct child of role="listbox"
    // — no <li> wrapper. The <ul> container is rendered with display:block
    // styling so removing the <li> doesn't change visuals.
    return `<button type="button" role="option" aria-selected="${isActive}" data-lang-code="${code}" class="w-full text-left px-3 py-2 text-[10px] font-mono uppercase tracking-widest ${activeClass} transition-colors flex items-center justify-between gap-3">
      <span>${name}</span><span class="opacity-50 text-[8px]">${code.toUpperCase()}</span>
    </button>`;
  }).join('');
  dd.querySelectorAll('[data-lang-code]').forEach(btn => {
    btn.addEventListener('click', () => {
      const code = btn.getAttribute('data-lang-code');
      if (!code || code === AppState.language) {
        dd.classList.add('hidden');
        return;
      }
      AppState.language = code;
      try { localStorage.setItem('lexicon-lang', code); } catch(e) {}
      dd.classList.add('hidden');
      $('btn-lang-toggle')?.setAttribute('aria-expanded', 'false');
      refreshUI();
      showToast(getTranslation('toast_language', code) + ' ' + code.toUpperCase());
    });
  });
}

function toggleLangDropdown() {
  const dd = $('lang-dropdown');
  const btn = $('btn-lang-toggle');
  if (!dd) return;
  const isHidden = dd.classList.contains('hidden');
  dd.classList.toggle('hidden');
  if (btn) btn.setAttribute('aria-expanded', isHidden ? 'true' : 'false');
  // When opening, move focus to the currently selected option (or first).
  if (isHidden) {
    const selected = dd.querySelector('[aria-selected="true"]') || dd.querySelector('[role="option"]');
    if (selected) requestAnimationFrame(() => selected.focus());
  }
}

// Keyboard navigation for lang dropdown (listbox semantics).
document.addEventListener('keydown', (e) => {
  const dd = document.getElementById('lang-dropdown');
  if (!dd || dd.classList.contains('hidden')) return;
  if (!dd.contains(document.activeElement)) return;
  const options = Array.from(dd.querySelectorAll('[role="option"]'));
  if (!options.length) return;
  const idx = options.indexOf(document.activeElement);
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    options[(idx + 1) % options.length].focus();
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    options[(idx - 1 + options.length) % options.length].focus();
  } else if (e.key === 'Home') {
    e.preventDefault();
    options[0].focus();
  } else if (e.key === 'End') {
    e.preventDefault();
    options[options.length - 1].focus();
  } else if (e.key === 'Escape') {
    e.preventDefault();
    dd.classList.add('hidden');
    document.getElementById('btn-lang-toggle')?.setAttribute('aria-expanded', 'false');
    document.getElementById('btn-lang-toggle')?.focus();
  }
});

function toggleLanguage() {
  let idx = supportedLanguages.indexOf(AppState.language);
  idx = (idx + 1) % supportedLanguages.length;
  AppState.language = supportedLanguages[idx];
  try { localStorage.setItem('lexicon-lang', AppState.language); } catch(e) {}
  refreshUI();
  showToast(getTranslation('toast_language', AppState.language) + ' ' + AppState.language.toUpperCase());
}

function renderFoldersView() {
  const container = $('folders-grid');
  if (!container) return;
  container.innerHTML = '';
  if (AppState.archivalFolders.length === 0) {
    container.innerHTML = `<p class="text-[10px] font-mono uppercase opacity-40">${getTranslation('folder_no_detected', AppState.language)}</p>`;
    return;
  }
  AppState.archivalFolders.forEach(fol => {
    const card = document.createElement('div');
    card.className = 'bg-bone dark:bg-darkBase border border-black dark:border-white p-6 cursor-crosshair hover:bg-black hover:text-white dark:hover:bg-acid dark:hover:text-black transition-all focus-ring';
    card.setAttribute('role', 'button');
    card.setAttribute('tabindex', '0');
    card.setAttribute('aria-label', `Open folder ${fol.name}, ${fol.lookIds ? fol.lookIds.length : 0} entries`);
    card.innerHTML = `
      <div class="flex items-baseline justify-between mb-4">
        <h3 class="text-xs font-bold font-mono uppercase tracking-[0.1em]">${fol.name}</h3>
        <button type="button" class="btn-export-fol text-[9px] font-mono uppercase opacity-40 group-hover:opacity-100 underline" aria-label="Export folder ${fol.name} as JSON">EXPORT_JSON</button>
      </div>
      <p class="text-[10px] font-mono opacity-60 mb-4">${fol.notes ? fol.notes : getTranslation('no_obs_logged', AppState.language)}</p>
      <div class="flex gap-6 text-[9px] font-mono uppercase opacity-50">
        <span>${fol.lookIds ? fol.lookIds.length : 0} ${getTranslation('artifacts_count', AppState.language)}</span>
        <span>${new Date(fol.createdAt).toLocaleDateString()}</span>
      </div>
    `;
    const open = () => {
      AppState.activeFolderId = fol.id;
      switchView('grid', callbacks);
      showToast(getTranslation('toast_browsing', AppState.language) + ' ' + fol.name);
    };
    card.addEventListener('click', (e) => {
      if (e.target.classList.contains('btn-export-fol')) { e.stopPropagation(); exportFolder(fol.id); return; }
      open();
    });
    card.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' || e.key === ' ') {
        if (e.target.classList.contains('btn-export-fol')) return;
        e.preventDefault();
        open();
      }
    });
    container.appendChild(card);
  });
}

function renderSaveFolderModal() {
  const container = $('folder-list-container');
  if (!container) return;
  container.innerHTML = '';
  if (AppState.archivalFolders.length === 0) {
    container.innerHTML = `<p class="text-[10px] font-mono uppercase opacity-40">${getTranslation('folder_no_existing', AppState.language)}</p>`;
    return;
  }
  AppState.archivalFolders.forEach(fol => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'w-full text-left border border-black/10 dark:border-white/10 p-3 text-[10px] font-mono uppercase tracking-widest hover:bg-black hover:text-white dark:hover:bg-acid dark:hover:text-black transition-colors flex justify-between items-center focus-ring';
    const count = fol.lookIds ? fol.lookIds.length : 0;
    btn.setAttribute('aria-label', `Save to folder ${fol.name}, ${count} entries`);
    btn.innerHTML = `<span>${fol.name}</span><span class="opacity-40" aria-hidden="true">${count}</span>`;
    btn.addEventListener('click', () => {
      saveToFolder(fol.id, AppState.selectedEntryId, callbacks);
      const modal = $('save-folder-modal');
      if (modal) modal.classList.add('hidden');
      restoreFocus();
    });
    container.appendChild(btn);
  });
}

function exportFolder(folId) {
  const fol = AppState.archivalFolders.find(f => f.id === folId);
  if (!fol) return;
  const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(fol, null, 2));
  const a = document.createElement('a');
  a.setAttribute('href', dataStr);
  a.setAttribute('download', `lexicon_folder_${fol.name.toLowerCase()}.json`);
  a.click();
}

function exportAllFolders() {
  const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(AppState.archivalFolders, null, 2));
  const a = document.createElement('a');
  a.setAttribute('href', dataStr);
  a.setAttribute('download', 'lexicon_all_folders.json');
  a.click();
}

