// AUTO-GENERATED by .github/scripts/inject-env.mjs — do not edit by hand.
// Stamped at build time from environment variables. Never commit real values.
// To regenerate locally: node .github/scripts/inject-env.mjs (needs .env.local)
export const SUPABASE_URL      = '';
export const SUPABASE_ANON_KEY = '';
export const USE_SUPABASE      = false;
