#!/usr/bin/env node
/**
 * Regenerate reviews.js from content/reviews/*.json.
 *
 * The JSON files are the source of truth. reviews.js is a build artifact
 * — committed alongside the JSON so it can be served without a build step,
 * but never edited by hand.
 *
 * Unlike entries, reviews have no order.json — display order is always
 * reverse-chronological by publishedAt, computed here at build time.
 *
 * Adding a new review:
 *   1. Drop content/reviews/<slug>.json (validated by review.schema.json).
 *   2. Run `npm run build-reviews` (also runs automatically in preflight).
 *   3. Commit both the new JSON and the updated reviews.js + reviews/<slug>/.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT    = fileURLToPath(new URL('../../', import.meta.url));
const REVIEWS = join(ROOT, 'content', 'reviews');
const OUT     = join(ROOT, 'reviews.js');

// Skip _template.json and similar drafts.
const files = readdirSync(REVIEWS).filter(f => f.endsWith('.json') && !f.startsWith('_'));

const reviews = files
  .map(f => JSON.parse(readFileSync(join(REVIEWS, f), 'utf8')))
  .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));

const banner = `/**
 * AUTO-GENERATED by .github/scripts/build-reviews.mjs from content/reviews/*.json.
 * Do not edit by hand. To change a review, edit its JSON file and run
 * \`npm run build-reviews\`. Order is always reverse-chronological by publishedAt.
 */
`;

writeFileSync(OUT, banner + 'export const reviewsData = ' + JSON.stringify(reviews, null, 2) + ';\n', 'utf8');
console.log(`Wrote ${OUT} (${reviews.length} reviews)`);
