#!/usr/bin/env node
/**
 * Regenerate database.js from content/entries/*.json + content/order.json.
 *
 * The JSON files are the source of truth. database.js is a build artifact
 * — committed alongside the JSON so GitHub Pages can serve it without a
 * build step, but never edited by hand.
 *
 * Adding a new entry:
 *   1. Drop content/entries/<id>.json (validated by entry.schema.json).
 *   2. Add "<id>" to content/order.json (controls grid display order).
 *   3. Run `npm run build-data` (also runs automatically in prebuild).
 *   4. Commit both the new JSON and the updated database.js.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT     = fileURLToPath(new URL('../../', import.meta.url));
const ENTRIES  = join(ROOT, 'content', 'entries');
const ORDER    = join(ROOT, 'content', 'order.json');
const OUT      = join(ROOT, 'database.js');

const order = JSON.parse(readFileSync(ORDER, 'utf8'));
if (!Array.isArray(order)) throw new Error('content/order.json must be a JSON array of entry ids');

// Skip _template.json and similar drafts.
const filesInDir = new Set(readdirSync(ENTRIES).filter(f => f.endsWith('.json') && !f.startsWith('_')).map(f => f.replace(/\.json$/, '')));
const orphan = [...filesInDir].filter(id => !order.includes(id));
const missing = order.filter(id => !filesInDir.has(id));
if (orphan.length)  throw new Error('entries on disk but not in order.json: ' + orphan.join(', '));
if (missing.length) throw new Error('ids in order.json but no entry file: ' + missing.join(', '));

const archive = order.map(id => JSON.parse(readFileSync(join(ENTRIES, id + '.json'), 'utf8')));

const banner = `/**
 * AUTO-GENERATED by .github/scripts/build-data.mjs from content/entries/*.json.
 * Do not edit by hand. To change an entry, edit its JSON file and run
 * \`npm run build-data\`. To change ordering, edit content/order.json.
 */
`;

writeFileSync(OUT, banner + 'export const archiveData = ' + JSON.stringify(archive, null, 2) + ';\n', 'utf8');
console.log(`Wrote ${OUT} (${archive.length} entries)`);
