#!/usr/bin/env node
/**
 * .github/scripts/inject-env.mjs
 * ─────────────────────────────────────────────────────────────────────────────
 * Generates js/env.js from environment variables at build time.
 *
 * In Vercel production:
 *   Set SUPABASE_URL and SUPABASE_ANON_KEY in the project's Environment
 *   Variables dashboard. Vercel injects them automatically before running
 *   the buildCommand.
 *
 * Locally (optional — the app falls back to database.js without them):
 *   Copy .env.example → .env.local and fill in your values, then:
 *     node .github/scripts/inject-env.mjs
 *
 * The generated js/env.js is committed as an empty-value placeholder so
 * the ES module import never 404s in local dev without a prior build.
 * The real values only ever live in build environments, never in the repo.
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { join, dirname }              from 'node:path';
import { fileURLToPath }              from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

// ── Load .env.local for local invocations ────────────────────────────────────
try {
  const raw = readFileSync(join(ROOT, '.env.local'), 'utf8');
  for (const line of raw.split('\n')) {
    const eq = line.indexOf('=');
    if (eq < 1) continue;
    const k = line.slice(0, eq).trim();
    const v = line.slice(eq + 1).trim();
    if (k && v && !process.env[k]) process.env[k] = v;
  }
} catch { /* no .env.local is fine */ }

const url = process.env.SUPABASE_URL      || '';
const key = process.env.SUPABASE_ANON_KEY || '';
const use = !!(url && key);

const out = `// AUTO-GENERATED by .github/scripts/inject-env.mjs — do not edit by hand.
// Stamped at build time from environment variables. Never commit real values.
// To regenerate locally: node .github/scripts/inject-env.mjs (needs .env.local)
export const SUPABASE_URL      = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
export const USE_SUPABASE      = ${use};
`;

writeFileSync(join(ROOT, 'js', 'env.js'), out, 'utf8');
console.log(`INJECT_ENV ok  (USE_SUPABASE=${use})`);
