#!/usr/bin/env node
/**
 * .github/scripts/inject-env.mjs
 * ─────────────────────────────────────────────────────────────────────────────
 * Validates that required Vercel environment variables are present at build
 * time, then writes js/env.js with any front-end-visible values.
 *
 * Required Vercel env vars (set in project dashboard, never commit):
 *   DATABASE_URL   — Neon Postgres connection string
 *   RESEND_API_KEY — Resend transactional email API key
 *   APP_ORIGIN     — https://thelexicon.xyz (no trailing slash)
 *
 * None of these are exposed to the browser; they're used only in /api/*.
 * js/env.js is a front-end module — keep it free of secrets.
 *
 * Locally: no env vars needed for the SPA itself. The /api functions
 * require a .env.local with the vars above if testing locally with
 * `vercel dev`.
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { join, dirname }              from 'node:path';
import { fileURLToPath }              from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

// Load .env.local for local invocations
try {
  const raw = readFileSync(join(ROOT, '.env.local'), 'utf8');
  for (const line of raw.split('\n')) {
    const eq = line.indexOf('=');
    if (eq < 1) continue;
    const k = line.slice(0, eq).trim();
    const v = line.slice(eq + 1).trim();
    if (k && v && !process.env[k]) process.env[k] = v;
  }
} catch { /* no .env.local is fine in CI */ }

// Warn (not fail) if backend vars are missing — the SPA works without auth.
const required = ['DATABASE_URL', 'RESEND_API_KEY', 'APP_ORIGIN'];
const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.warn(`INJECT_ENV warn — missing backend env vars: ${missing.join(', ')}`);
  console.warn('  Sign-in will not work until these are set in Vercel dashboard.');
}

// js/env.js is a browser module — no secrets go here.
const out = `// AUTO-GENERATED by .github/scripts/inject-env.mjs — do not edit by hand.
// Stamped at build time. Never commit secrets here.
export const APP_ORIGIN = ${JSON.stringify(process.env.APP_ORIGIN || 'https://thelexicon.xyz')};
`;

writeFileSync(join(ROOT, 'js', 'env.js'), out, 'utf8');
console.log('INJECT_ENV ok');
