/* === ARCHIVE DATA ENGINE === */
const archiveData = [
  {
    id: 'mcqueen-ss99',
    title: 'Alexander McQueen SS 1999',
    subtitle: 'No. 13',
    year: 1999,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-01.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-02.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-03.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-04.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-05.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-06.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-07.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-08.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-09.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-10.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-11.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-12.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-13.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-14.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-15.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-16.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-01.jpg',
    description: '',
    tags: { brand: 'Alexander McQueen', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'mugler-aw95',
    title: 'Thierry Mugler AW 1995',
    subtitle: 'Anniversaire',
    year: 1995,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-01.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-02.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-03.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-04.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-05.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-06.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-07.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-08.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-09.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-10.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-11.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-12.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-13.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-14.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-15.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-16.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-01.jpg',
    description: '',
    tags: { brand: 'Thierry Mugler', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'miyake-ss99',
    title: 'Issey Miyake SS 1999',
    subtitle: 'A-POC',
    year: 1999,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-01.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-02.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-03.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-04.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-05.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-06.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-07.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-08.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-09.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-10.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-11.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-12.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-13.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-14.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-01.jpg',
    description: '',
    tags: { brand: 'Issey Miyake', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'balenciaga-ss07',
    title: 'Balenciaga SS 2007',
    subtitle: 'Robotic Articulation',
    year: 2007,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-01.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-02.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-03.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-04.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-05.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-06.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-07.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-08.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-09.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-10.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-11.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-12.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-13.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-14.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-01.jpg',
    description: '',
    tags: { brand: 'Balenciaga', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'chalayan-aw00',
    title: 'Hussein Chalayan AW 2000',
    subtitle: 'After Words',
    year: 2000,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-01.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-02.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-03.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-04.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-05.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-06.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-07.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-09.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-10.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-11.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-12.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-13.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-14.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-01.jpg',
    description: '',
    tags: { brand: 'Hussein Chalayan', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'prada-ss96',
    title: 'Prada SS 1996',
    subtitle: 'Banal Eccentricity',
    year: 1996,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-01.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-02.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-03.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-04.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-05.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-06.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-07.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-08.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-09.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-10.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-11.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-12.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-13.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-14.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-01.jpg',
    description: '',
    tags: { brand: 'Prada', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'galliano-dior-ss00',
    title: 'John Galliano for Dior Couture SS 2000',
    subtitle: 'Clochard',
    year: 2000,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-01.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-02.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-03.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-04.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-05.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-06.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-07.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-08.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-09.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-10.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-11.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-12.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-13.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-14.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-01.jpg',
    description: '',
    tags: { brand: 'John Galliano for Dior', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'owens-ss14',
    title: 'Rick Owens SS 2014',
    subtitle: 'Vicious',
    year: 2014,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-01.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-02.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-03.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-04.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-05.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-06.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-07.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-08.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-09.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-10.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-11.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-12.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-13.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-14.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-01.jpg',
    description: '',
    tags: { brand: 'Rick Owens', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'garcons-ss97',
    title: 'Comme des Garçons SS 1997',
    subtitle: 'Body Meets Dress; Dress Meets Body',
    year: 1997,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-01.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-02.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-03.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-04.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-05.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-06.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-07.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-08.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-09.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-10.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-11.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-12.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-13.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-14.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-01.jpg',
    description: '',
    tags: { brand: 'Comme des Garçons', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'yamamoto-aw98',
    title: 'Yohji Yamamoto AW 1998',
    subtitle: '',
    year: 1998,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-01.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-02.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-03.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-04.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-05.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-06.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-07.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-08.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-09.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-10.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-11.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-12.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-13.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-14.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-01.jpg',
    description: '',
    tags: { brand: 'Yohji Yamamoto', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'gaultier-ss94',
    title: 'Jean Paul Gaultier SS 1994',
    subtitle: 'Les Tatouages',
    year: 1994,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-01.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-02.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-03.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-04.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-05.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-06.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-07.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-08.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-09.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-10.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-11.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-12.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-13.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-14.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-15.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-16.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-01.jpg',
    description: '',
    tags: { brand: 'Jean Paul Gaultier', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'viktor-rolf-aw99',
    title: 'Viktor & Rolf AW 1999',
    subtitle: 'Russian Doll',
    year: 1999,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-01.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-02.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-03.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-04.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-05.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-06.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-07.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-01.jpg',
    description: '',
    tags: { brand: 'Viktor & Rolf', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'lang-aw98',
    title: 'Helmut Lang AW 1998',
    subtitle: 'Séance de Travail',
    year: 1998,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-01.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-02.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-03.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-04.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-05.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-06.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-07.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-08.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-09.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-10.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-01.jpg',
    description: '',
    tags: { brand: 'Helmut Lang', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'moschino-aw14',
    title: 'Moschino AW 2014',
    subtitle: '',
    year: 2014,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-01.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-02.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-04.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-05.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-06.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-07.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-08.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-09.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-10.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-11.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-12.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-13.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-14.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-01.jpg',
    description: '',
    tags: { brand: 'Moschino', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'schiaparelli-ss21',
    title: 'Schiaparelli Haute Couture SS 2021',
    subtitle: '',
    year: 2021,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-01.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-02.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-03.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-04.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-05.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-06.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-07.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-08.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-09.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-10.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-11.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-12.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-13.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-14.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-01.jpg',
    description: '',
    tags: { brand: 'Schiaparelli', era: '', politics: '', theories: '', gender: '', materials: '', geography: '', form: '', format: '' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
];
