/* === ARCHIVE DATA ENGINE === */
const archiveData = [
  {
    id: 'mcqueen-ss99',
    title: 'Alexander McQueen SS 1999',
    subtitle: 'No. 13',
    year: 1999,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-01.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-02.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-03.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-04.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-05.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-06.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-07.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-08.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-09.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-10.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-11.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-12.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-13.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-14.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-15.jpg',
      'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-16.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/mcqueen-ss99/mcqueen-ss99-01.jpg',
    description: '',
    tags: { brand: 'Alexander McQueen', era: '1990s', politics: 'Disability; Vulnerability; Power', theories: 'Performance Art; Constriction as Power', gender: 'Feminine; Weaponised', materials: 'Lace; Leather; Bone-Pale Silks; Carved Wood', geography: 'London', form: 'Cage Constructions; Prosthetic Legs; Paint-Sprayed Finale', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'mugler-aw95',
    title: 'Thierry Mugler AW 1995',
    subtitle: 'Anniversaire',
    year: 1995,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-01.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-02.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-03.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-04.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-05.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-06.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-07.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-08.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-09.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-10.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-11.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-12.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-13.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-14.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-15.jpg',
      'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-16.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/mugler-aw95/mugler-aw95-01.jpg',
    description: '',
    tags: { brand: 'Thierry Mugler', era: '1990s', politics: 'Age; Glamour; Hyperbolic Femininity', theories: 'Exoskeletal Body Construction; Silhouette as Architecture', gender: 'Hyperbolic Feminine', materials: 'Latex; Chrome; Hand-Beaten Metal; Leather; Silk', geography: 'Paris', form: 'Sculptural Shoulders; Cinched Waists; Metallic Breastplates', format: 'Haute Couture' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'miyake-ss99',
    title: 'Issey Miyake SS 1999',
    subtitle: 'A-POC',
    year: 1999,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-01.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-02.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-03.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-04.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-05.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-06.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-07.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-08.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-09.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-10.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-11.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-12.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-13.jpg',
      'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-14.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/miyake-ss99/miyake-ss99-01.jpg',
    description: '',
    tags: { brand: 'Issey Miyake', era: '1990s', politics: 'Zero-Waste Manufacturing; Communal Garment Systems', theories: 'A-POC Technology; Body-Textile Connectivity', gender: 'Body-Neutral', materials: 'Continuous Knit Tubes; Red Jersey; Industrial Knitting', geography: 'Paris', form: 'Connected Knit Tubes; Pre-Cut Wearable Systems', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'balenciaga-ss07',
    title: 'Balenciaga SS 2007',
    subtitle: 'Robotic Articulation',
    year: 2007,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-01.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-02.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-03.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-04.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-05.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-06.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-07.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-08.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-09.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-10.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-11.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-12.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-13.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-14.jpg',
      'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/balenciaga-ss07/balenciaga-ss07-01.jpg',
    description: '',
    tags: { brand: 'Balenciaga', era: '2000s', politics: 'Cyborg Femininity; Technological Transcendence', theories: 'Robotic Articulation; Mechanical Body Transformation', gender: 'Androgynous', materials: 'Patent Leather; Moulded Plastics; Articulated Metal; Neoprene', geography: 'Paris', form: 'Exoskeletal Structures; Robotic Leggings; Hard Shell Construction', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'chalayan-aw00',
    title: 'Hussein Chalayan AW 2000',
    subtitle: 'After Words',
    year: 2000,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-01.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-02.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-03.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-04.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-05.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-06.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-07.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-09.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-10.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-11.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-12.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-13.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-14.jpg',
      'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/chalayan-aw00/chalayan-aw00-01.jpg',
    description: '',
    tags: { brand: 'Hussein Chalayan', era: '2000s', politics: 'Refugee Displacement; Migration; War', theories: 'Fashion as Performance; Furniture-as-Garment', gender: 'Feminine', materials: 'Cotton; Mahogany; Metal; Leather; Tulle', geography: 'London', form: 'Transformable Furniture; Slipcover Dresses; Coffee Table Skirt', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'prada-ss96',
    title: 'Prada SS 1996',
    subtitle: 'Banal Eccentricity',
    year: 1996,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-01.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-02.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-03.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-04.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-05.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-06.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-07.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-08.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-09.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-10.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-11.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-12.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-13.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-14.jpg',
      'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/prada-ss96/prada-ss99-01.jpg',
    description: '',
    tags: { brand: 'Prada', era: '1990s', politics: 'Critique of Beauty; Anti-Aspirational Aesthetics', theories: 'Ugly Chic; Bad Taste as Intellectual Rigour', gender: 'Agnostic', materials: 'Nylon; Synthetic Blends; Clashing Prints', geography: 'Milan', form: 'Boxy Silhouettes; Awkward Proportions; Clashing Prints', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'galliano-dior-ss00',
    title: 'John Galliano for Dior Couture SS 2000',
    subtitle: 'Clochard',
    year: 2000,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-01.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-02.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-03.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-04.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-05.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-06.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-07.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-08.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-09.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-10.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-11.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-12.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-13.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-14.jpg',
      'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/galliano-dior-ss00/galliano-dior-ss00-01.jpg',
    description: '',
    tags: { brand: 'John Galliano for Dior', era: '2000s', politics: 'Luxury vs. Poverty; Homelessness; Class Aesthetics', theories: 'Couture Technique Applied to Street Destitution; Vionnet Bias-Cut', gender: 'Feminine', materials: 'Silk; Newspaper Prints; Distressed Fabrics; Safety Pins', geography: 'Paris', form: 'Bias-Cut Gowns; Elongated Trains; Enormous Sleeves', format: 'Haute Couture' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'owens-ss14',
    title: 'Rick Owens SS 2014',
    subtitle: 'Vicious',
    year: 2014,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-01.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-02.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-03.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-04.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-05.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-06.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-07.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-08.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-09.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-10.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-11.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-12.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-13.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-14.jpg',
      'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/owens-ss14/owens-ss14-01.jpg',
    description: '',
    tags: { brand: 'Rick Owens', era: '2010s', politics: 'Race; Body Diversity; HBCU Culture; Representation', theories: 'Clothing as Secondary to Body Performance; Communal Kinetic Identity', gender: 'Diverse; Gender-Fluid', materials: 'Leather; Draped Wool; Crepe Soles', geography: 'Paris', form: 'Draped Asymmetric Tunics; Long Leather Skirts; Platform Boots', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'garcons-ss97',
    title: 'Comme des Garçons SS 1997',
    subtitle: 'Body Meets Dress; Dress Meets Body',
    year: 1997,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-01.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-02.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-03.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-04.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-05.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-06.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-07.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-08.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-09.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-10.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-11.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-12.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-13.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-14.jpg',
      'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/garcons-ss97/garcons-ss97-01.jpg',
    description: '',
    tags: { brand: 'Comme des Garçons', era: '1990s', politics: 'Feminist Critique; Beauty Standards; Disabled Body', theories: 'Goose-Down Padding Distortion; Body as Material Substrate', gender: 'Feminine; Defeminised Through Distortion', materials: 'Stretch Nylon-Urethane; Gingham; Goose-Down Padding', geography: 'Paris', form: 'Padded Lumps and Bumps; Alien Silhouettes; Asymmetrical', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'yamamoto-aw98',
    title: 'Yohji Yamamoto AW 1998',
    subtitle: '',
    year: 1998,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-01.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-02.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-03.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-04.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-05.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-06.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-07.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-08.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-09.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-10.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-11.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-12.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-13.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-14.jpg',
      'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/yamamoto-aw98/yamamoto-aw98-01.jpg',
    description: '',
    tags: { brand: 'Yohji Yamamoto', era: '1990s', politics: 'Japanese-Western Tailoring Dialectic; Anti-Body Construction', theories: 'Volume as Independent System; Garment-as-Space', gender: 'Androgynous', materials: 'Dense Wools; Silks; Distressed Fabrics; Japanese Textiles', geography: 'Paris', form: 'Massive Asymmetric Coats; Extreme Volumetric Skirts; Architectural Crinoline', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'gaultier-ss94',
    title: 'Jean Paul Gaultier SS 1994',
    subtitle: 'Les Tatouages',
    year: 1994,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-01.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-02.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-03.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-04.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-05.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-06.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-07.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-08.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-09.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-10.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-11.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-12.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-13.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-14.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-15.jpg',
      'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-16.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/gaultier-ss94/gaultier-ss94-01.jpg',
    description: '',
    tags: { brand: 'Jean Paul Gaultier', era: '1990s', politics: 'Subcultural Identity; Gender Subversion; Cross-Cultural Hybridity', theories: 'Trompe L\'Oeil Tattoo Printing; Skin-Fabric Confusion', gender: 'Gender-Subversive', materials: 'Mesh; Denim; Metallic Knitwear; Sequins; Chainmail', geography: 'Paris', form: 'Patchwork Denim Couture; Tattoo-Print Mesh; Joan of Arc Armour', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'viktor-rolf-aw99',
    title: 'Viktor & Rolf AW 1999',
    subtitle: 'Russian Doll',
    year: 1999,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-01.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-02.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-03.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-04.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-05.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-06.jpg',
      'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-07.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/viktor-rolf-aw99/viktor-rolf-aw99-01.jpg',
    description: '',
    tags: { brand: 'Viktor & Rolf', era: '1990s', politics: 'Fashion Accumulation Theory; Body as Container', theories: 'Russian Matryoshka Nesting; Fashion Excess; Layering as Philosophy', gender: 'Feminine', materials: 'Silk; Couture Construction; Crinoline', geography: 'Paris', form: 'Progressive Layering; Increasing Volume; Silhouette Obliteration', format: 'Haute Couture' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'lang-aw98',
    title: 'Helmut Lang AW 1998',
    subtitle: 'Séance de Travail',
    year: 1998,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-01.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-02.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-03.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-04.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-05.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-06.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-07.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-08.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-09.jpg',
      'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-10.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/lang-aw98/lang-aw98-01.jpg',
    description: '',
    tags: { brand: 'Helmut Lang', era: '1990s', politics: 'Disruption of Fashion Calendar; Anti-Theatrical Aesthetic', theories: 'Utilitarian Precision; Bondage-Influenced Construction; CD-ROM Distribution', gender: 'Androgynous', materials: 'Nylon; Synthetic Blends; Technical Fabrics; Bonded Seams', geography: 'Paris', form: 'Tailored Jackets with Exposed Hardware; Bondage Straps', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'moschino-aw14',
    title: 'Moschino AW 2014',
    subtitle: '',
    year: 2014,
    season: 'AW',
    images: [
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-01.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-02.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-04.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-05.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-06.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-07.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-08.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-09.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-10.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-11.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-12.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-13.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-14.jpg',
      'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/moschino-aw14/moschino-aw14-01.jpg',
    description: '',
    tags: { brand: 'Moschino', era: '2010s', politics: 'Critique of Fashion Pretensions; Luxury vs. Mass Culture', theories: 'Sign System Mutation; Corporate Branding as Aesthetic Material', gender: 'Feminine', materials: 'Bouclé; Fast-Food Branded Imagery; Embroidery', geography: 'Milan', form: 'McDonald\'s-Branded Suits; Spongebob Jacquard; Fast-Food Packaging', format: 'Ready-to-Wear' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
  {
    id: 'schiaparelli-ss21',
    title: 'Schiaparelli Haute Couture SS 2021',
    subtitle: '',
    year: 2021,
    season: 'SS',
    images: [
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-01.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-02.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-03.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-04.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-05.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-06.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-07.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-08.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-09.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-10.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-11.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-12.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-13.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-14.jpg',
      'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-15.jpg',
    ],
    imageUrl: 'THE-LEXICON-ASSETS/schiaparelli-ss21/schiaparelli-ss21-01.jpg',
    description: '',
    tags: { brand: 'Schiaparelli', era: '2020s', politics: 'Bodily Autonomy; Weaponised Beauty; Anatomical Visibility', theories: 'Moulded Anatomical Breastplates; Trompe L\'Oeil Hardware; Surrealist Displacement', gender: 'Feminine; Anatomically Explicit', materials: 'Moulded Leather; Gold Cast Elements; Chain-Link; Shocking Pink', geography: 'Paris', form: 'Gilded Breastplate Torsos; Anatomical Sculpture; Trompe L\'Oeil Jewellery', format: 'Haute Couture' },
    notes: { critique: '', strategy: '', provenance: '' },
    hotspots: []
  },
];
